### ISSUE TITLE
crashes with Nougat Android OS 7

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#1201]
I got this report from an user for some of my games that were using old version of Ren'Py. I updated a good amount of games, but looking in the Google Play console, I had a crash even in the updated version. The error is the following one:

java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.load0(Runtime.java:914)
  at java.lang.System.load(System.java:1508)
  at org.renpy.android.PythonActivity.run(PythonActivity.java:258)
  at java.lang.Thread.run(Thread.java:776)

so before updating all my other games I wanted to be sure that isn't something else :)

**Comment by renpytom** [comment]
This is already fixed in the latest Ren'Py.
