### ISSUE TITLE
AttributeError: 'Sphinx' object has no attribute 'domains'

### ISSUE THREAD

**Issue by sl1pkn07** [renpy/renpy#1213]
Hi

when ret build the documentation (source) with sphinx, i get:

```
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[/tmp/makepkg/renpy-suite-git/src/renpy/sphinx]|
└───╼  sphinx-build2 -a source ../doc/
Running Sphinx v1.6.3

Exception occurred:
  File "/tmp/makepkg/renpy-suite-git/src/renpy/sphinx/source/renpydoc.py", line 158, in add_index
    app.domains[domain].indices.append(MyIndex)
AttributeError: 'Sphinx' object has no attribute 'domains'
The full traceback has been saved in /tmp/sphinx-err-XW_1p8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

```
# Sphinx version: 1.6.3
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python2.7/site-packages/sphinx/registry.py", line 207, in load_extension
    metadata = mod.setup(app)
  File "/tmp/makepkg/renpy-suite-git/src/renpy/sphinx/source/renpydoc.py", line 168, in setup
    add_index(app, "std", "style-property", "Style Property Index")
  File "/tmp/makepkg/renpy-suite-git/src/renpy/sphinx/source/renpydoc.py", line 158, in add_index
    app.domains[domain].indices.append(MyIndex)
AttributeError: 'Sphinx' object has no attribute 'domains'
```

is a sphinx or renpy doc error?

greetings

PS: also, when try build developer documentation, build ok, but get this warning:

```
checking consistency... /tmp/makepkg/renpy-suite-git/src/renpy/sphinx/developer/building.rst: WARNING: document isn't included in any toctree
/tmp/makepkg/renpy-suite-git/src/renpy/sphinx/developer/versioning.rst: WARNING: document isn't included in any toctree
/tmp/makepkg/renpy-suite-git/src/renpy/sphinx/developer/windows.rst: WARNING: document isn't included in any toctree
```

**Comment by renpytom** [comment]
Fixed by 33009207. The Ren'Py documentation doesn't build warning-free, yet.
