### ISSUE TITLE
[RAPT] NDK warning/crash on API 27 (Android 8.1)

### ISSUE THREAD

**Issue by saber-nyan** [renpy/renpy#1344]
When I run the [application](https://github.com/saber-nyan/ddlc-android/releases/tag/v0.0.4) it displays warning:

![Warning Toast](https://user-images.githubusercontent.com/25345196/34743733-e748b82e-f59b-11e7-9f72-a293040cae26.png)

Another person sent me a crash report. The crash occurs after a warning is displayed.
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/000statements.rpy", line 383, in execute_pause
error: Could not fetch native window

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/bootstrap.py", line 305, in bootstrap
    renpy.main.main()
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/main.py", line 499, in main
    run(restart)
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/main.py", line 147, in run
    renpy.execution.run_context(True)
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/execution.py", line 795, in run_context
    context.run()
  File "00start.rpyc", line 222, in script call
  File "splash.rpyc", line 257, in script
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/ast.py", line 1775, in execute
    self.call("execute")
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/ast.py", line 1763, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/statements.py", line 163, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 383, in execute_pause
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/exports.py", line 1406, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/display/core.py", line 2123, in do_with
    clear=clear)
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/display/core.py", line 2521, in interact
    self.start()
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/display/core.py", line 1711, in start
    self.set_mode()
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/display/core.py", line 1941, in set_mode
    if draw.set_mode(virtual_size, physical_size, fullscreen):
  File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/display/swdraw.py", line 763, in set_mode
    self.screen = pygame.display.set_mode((scaled_width, scaled_height), fsflag, 32)
  File "src/pygame_sdl2/display.pyx", line 438, in pygame_sdl2.display.set_mode (gen/pygame_sdl2.display.c:6434)
  File "src/pygame_sdl2/display.pyx", line 168, in pygame_sdl2.display.Window.__init__ (gen/pygame_sdl2.display.c:2942)
error: Could not fetch native window
```

Logcat:
```
01-09 16:14:45.177  4339  4363 V python  : Starting preparePython.
01-09 16:14:45.261  4339  4363 V python  : Extracting private assets.
01-09 16:14:45.265  4339  4363 I python  : extracting private.mp3 to /data/user/0/ru.saber_nyan.ddlc/files
01-09 16:14:46.876  4339  4363 V python  : Finished preparePython.
01-09 16:14:46.876  4339  4363 I python  : Initialize Python for Android
01-09 16:14:46.936  4339  4363 I python  : ['/data/user/0/ru.saber_nyan.ddlc/files/lib/python2.7/site-packages', '/data/user/0/ru.saber_nyan.ddlc/files/lib/site-python']
01-09 16:14:46.936  4339  4363 I python  : 3...
01-09 16:14:46.936  4339  4363 I python  : 2...
01-09 16:14:46.936  4339  4363 I python  : 1...
01-09 16:14:46.936  4339  4363 I python  : Android path ['/data/user/0/ru.saber_nyan.ddlc/files', '/data/user/0/ru.saber_nyan.ddlc/files/lib/python27.zip', '/data/user/0/ru.saber_nyan.ddlc/files/lib/python2.7', '/data/user/0/ru.saber_nyan.ddlc/files/lib/python2.7/lib-dynload', '/data/user/0/ru.saber_nyan.ddlc/files/lib/python2.7/site-packages']
01-09 16:14:46.936  4339  4363 I python  : Android bootstrap done. __name__ is __main__
01-09 16:14:46.991  4339  4363 I python  : Run user program, change dir and execute main.py
01-09 16:14:49.174  4339  4363 I python  : Using expansion file /storage/emulated/0/Android/obb/ru.saber_nyan.ddlc/main.4.ru.saber_nyan.ddlc.obb
01-09 16:14:49.174  4339  4363 I python  : Traceback (most recent call last):
01-09 16:14:49.174  4339  4363 I python  :   File "/data/user/0/ru.saber_nyan.ddlc/files/renpy/log.py", line 96, in open
01-09 16:14:49.174  4339  4363 I python  :     fn = os.path.join(base, self.name + ".txt")
01-09 16:14:49.174  4339  4363 I python  :   File "/data/user/0/ru.saber_nyan.ddlc/files/lib/python2.7/posixpath.py", line 68, in join
01-09 16:14:49.174  4339  4363 I python  :     elif path == '' or path.endswith('/'):
01-09 16:14:49.174  4339  4363 I python  : AttributeError: 'NoneType' object has no attribute 'endswith'
01-09 16:14:49.974  4339  4363 I python  : Bootstrap to the start of init.init took 0.00s
01-09 16:14:49.977  4339  4363 I python  : Manufacturer Google model Android SDK built for x86
01-09 16:14:50.030  4339  4363 I python  : Screen diagonal is 4.58938993767 inches.
01-09 16:14:50.030  4339  4363 I python  : Early init took 0.06s
01-09 16:14:50.032  4339  4363 I python  : Loader init took 0.00s
01-09 16:14:50.074  4339  4363 I python  : Loading error handling took 0.04s
01-09 16:14:51.665  4339  4363 I python  : game/script-poemgame.rpy:285: SyntaxWarning: name 'sayoriTime' is used prior to global declaration
01-09 16:14:51.666  4339  4363 I python  : game/script-poemgame.rpy:292: SyntaxWarning: name 'natsukiTime' is used prior to global declaration
01-09 16:14:51.666  4339  4363 I python  : game/script-poemgame.rpy:299: SyntaxWarning: name 'yuriTime' is used prior to global declaration
01-09 16:14:51.666  4339  4363 I python  : game/script-poemgame.rpy:306: SyntaxWarning: name 'monikaTime' is used prior to global declaration
01-09 16:14:51.782  4339  4363 I python  : Loading script took 1.71s
01-09 16:14:51.782  4339  4363 I python  : Saving to /storage/emulated/0/Android/data/ru.saber_nyan.ddlc/files/saves
01-09 16:14:51.784  4339  4363 I python  : Loading persistent took 0.00s
01-09 16:14:52.013  4339  4363 I python  : Running init code took 0.23s
01-09 16:14:52.013  4339  4363 I python  : Loading analysis data took 0.00s
01-09 16:14:52.134  4339  4363 I python  : Analyze and compile ATL took 0.12s
01-09 16:14:52.134  4339  4363 I python  : Index archives took 0.00s
01-09 16:14:52.134  4339  4363 I python  : Dump and make backups. took 0.00s
01-09 16:14:52.134  4339  4363 I python  : Cleaning cache took 0.00s
01-09 16:14:52.134  4339  4363 I python  : Making clean stores took 0.00s
01-09 16:14:52.737  4339  4363 I python  : Creating interface object took 0.60s
01-09 16:14:52.737  4339  4363 I python  : Cleaning stores took 0.00s
01-09 16:14:52.786  4339  4363 I python  : Init translation took 0.05s
01-09 16:14:52.790  4339  4363 I python  : Build styles took 0.00s
01-09 16:14:52.791  4339  4363 I python  : Load screen analysis took 0.00s
01-09 16:14:52.820  4339  4363 I python  : Analyze screens took 0.03s
01-09 16:14:52.879  4339  4363 I python  : Save screen analysis took 0.06s
01-09 16:14:53.029  4339  4363 I python  : Prepare screens took 0.15s
01-09 16:14:53.167  4339  4363 I python  : Save pyanalysis. took 0.14s
01-09 16:14:53.208  4339  4363 I python  : Save bytecode. took 0.04s
01-09 16:14:53.210  4339  4363 I python  : Running _start took 0.00s
01-09 16:14:53.246  4339  4363 I python  : Interface start took 0.04s
01-09 16:14:53.447  4339  4363 I python  : Total time until interface ready: 4.12511897087s
```

**Comment by renpytom** [comment]
Hi there. I can't give support on pirate games. Can you resubmit the issue on a game you own the rights to?
