### ISSUE TITLE
[RAPT] NDK warning/crash on API 27 (Android 8.1)

### ISSUE THREAD

**Issue by saber-nyan** [renpy/renpy#1345]
(from #1344)
APK: [saber-nyan/test-renpy-vn](https://github.com/saber-nyan/test-renpy-vn/releases)

Screenshot:

![image](https://user-images.githubusercontent.com/25345196/34747391-21b359d0-f5a9-11e7-8051-572d66f5da4e.png)

Logcat:
```
--------- beginning of main
--------- beginning of system
01-09 17:47:55.396  3794  3812 V python  : Starting preparePython.
01-09 17:47:55.411  3794  3812 V python  : Finished preparePython.
01-09 17:47:55.411  3794  3812 I python  : Initialize Python for Android
01-09 17:47:55.432  3794  3812 I python  : ['/data/user/0/ru.saber_nyan.trv/files/lib/python2.7/site-packages', '/data/user/0/ru.saber_nyan.trv/files/lib/site-python'] 01-09 17:47:55.432  3794  3812 I python  : 3...
01-09 17:47:55.432  3794  3812 I python  : 2...
01-09 17:47:55.432  3794  3812 I python  : 1...
01-09 17:47:55.432  3794  3812 I python  : Android path ['/data/user/0/ru.saber_nyan.trv/files', '/data/user/0/ru.saber_nyan.trv/files/lib/python27.zip', '/data/user/0/ru.saber_nyan.trv/files/lib/python2.7', '/data/user/0/ru.saber_nyan.trv/files/lib/python2.7/lib-dynload', '/data/user/0/ru.saber_nyan.trv/files/lib/python2.7/site-packages']
01-09 17:47:55.432  3794  3812 I python  : Android bootstrap done. __name__ is __main__
01-09 17:47:55.441  3794  3812 I python  : Run user program, change dir and execute main.py
01-09 17:47:55.470  3794  3812 I python  : Opening APK '/data/app/ru.saber_nyan.trv-Cs0u1fuedSHY46YpaXdPwg==/base.apk'
01-09 17:47:55.470  3794  3812 I python  : Traceback (most recent call last):
01-09 17:47:55.470  3794  3812 I python  :   File "/data/user/0/ru.saber_nyan.trv/files/renpy/log.py", line 96, in open
01-09 17:47:55.470  3794  3812 I python  :     fn = os.path.join(base, self.name + ".txt")
01-09 17:47:55.470  3794  3812 I python  :   File "/data/user/0/ru.saber_nyan.trv/files/lib/python2.7/posixpath.py", line 68, in join
01-09 17:47:55.470  3794  3812 I python  :     elif path == '' or path.endswith('/'):
01-09 17:47:55.470  3794  3812 I python  : AttributeError: 'NoneType' object has no attribute 'endswith'
01-09 17:47:55.564  3794  3812 I python  : Not using expansion file.
01-09 17:47:55.564  3794  3812 I python  : Opening APK '/data/app/ru.saber_nyan.trv-Cs0u1fuedSHY46YpaXdPwg==/base.apk'
01-09 17:47:55.569  3794  3812 I python  : Opening APK '/data/app/ru.saber_nyan.trv-Cs0u1fuedSHY46YpaXdPwg==/base.apk'
01-09 17:47:55.704  3794  3812 I python  : Bootstrap to the start of init.init took 0.00s
01-09 17:47:55.709  3794  3812 I python  : Manufacturer Google model Android SDK built for x86
01-09 17:47:55.744  3794  3812 I python  : Screen diagonal is 4.58938993767 inches.
01-09 17:47:55.748  3794  3812 I python  : Early init took 0.04s
01-09 17:47:55.754  3794  3812 I python  : Loader init took 0.01s
01-09 17:47:55.803  3794  3812 I python  : Loading error handling took 0.05s
01-09 17:47:55.899  3794  3812 I python  : Loading script took 0.10s
01-09 17:47:55.900  3794  3812 I python  : Saving to /storage/emulated/0/Android/data/ru.saber_nyan.trv/files/saves
01-09 17:47:55.902  3794  3812 I python  : Loading persistent took 0.00s
01-09 17:47:55.959  3794  3812 I python  : Running init code took 0.06s
01-09 17:47:55.975  3794  3812 I python  : Loading analysis data took 0.02s
01-09 17:47:55.978  3794  3812 I python  : Analyze and compile ATL took 0.00s
01-09 17:47:55.978  3794  3812 I python  : Index archives took 0.00s
01-09 17:47:55.978  3794  3812 I python  : Dump and make backups. took 0.00s
01-09 17:47:55.978  3794  3812 I python  : Cleaning cache took 0.00s
01-09 17:47:55.979  3794  3812 I python  : Making clean stores took 0.00s
01-09 17:47:55.992  3794  3812 I python  : Creating interface object took 0.01s
01-09 17:47:55.992  3794  3812 I python  : Cleaning stores took 0.00s
01-09 17:47:56.048  3794  3812 I python  : Init translation took 0.06s
01-09 17:47:56.058  3794  3812 I python  : Build styles took 0.01s
01-09 17:47:56.058  3794  3812 I python  : Load screen analysis took 0.00s
01-09 17:47:56.070  3794  3812 I python  : Analyze screens took 0.01s
01-09 17:47:56.165  3794  3812 I python  : Save screen analysis took 0.10s
01-09 17:47:56.217  3794  3812 I python  : Prepare screens took 0.05s
01-09 17:47:56.217  3794  3812 I python  : Save pyanalysis. took 0.00s
01-09 17:47:56.217  3794  3812 I python  : Save bytecode. took 0.00s
01-09 17:47:56.218  3794  3812 I python  : Running _start took 0.00s
01-09 17:47:56.232  3794  3812 I python  : Interface start took 0.01s
01-09 17:47:56.397  3794  3812 I python  : Total time until interface ready: 0.767634868622s
```

Related topic: [android-developers.googleblog.com](https://android-developers.googleblog.com/2016/06/android-changes-for-ndk-developers.html)

**Comment by Alienfab** [comment]
how do you updated the rapt android version?

**Comment by renpytom** [comment]
I believe this has been obsoleted by Ren'Py 7.1.
