### ISSUE TITLE
Atom package manager on Linux appears to be missing a few dependencies.

### ISSUE THREAD

**Issue by jghibiki** [renpy/renpy#1391]
When I launch the atom installation bundled with renpy, and attempt to go to Preferences -> Install I would get the following error:

```
    throw err;
    ^

Error: Cannot find module 'tmp'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jghibiki/Renpy/atom/atom-linux-x86_64/resources/app/apm/node_modules/asar/lib/filesystem.js:8:9)
    at Object.<anonymous> (/home/jghibiki/Renpy/atom/atom-linux-x86_64/resources/app/apm/node_modules/asar/lib/filesystem.js:168:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

This error was preventing me from installing themes, or other atom packages.

I was able to remediate the issue by going to the ```~/<renpy install>/atom/atom-linux-x86_64/resources```, and then running the following command:

```
npm install tmp npm
```

It appears (for the linux version at least) that the Atom Package Manager install is missing some dependencies. Since I did this I have been able to install themes and modules again.

Helpful info:
OS: Arch Linux
Install Method: Direct download from Renpy website. (i.e. no package manager)
```
uname -a
Linux Matoko 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux
```

**Comment by renpytom** [comment]
Fixed it, thanks.
