### ISSUE TITLE
TypeError: must be string without null bytes, not str

### ISSUE THREAD

**Issue by Dreamtale** [renpy/renpy#1505]
`Sun Jul  8 17:33:40 2018
Unknown platform.
Ren'Py 7.0.0.196
 

Bootstrap to the start of init.init took 0.00s
Bootstrap to the start of init.init took 0.00s
Manufacturer samsung model SM-N920C
Screen diagonal is 5.24501707162 inches.
Early init took 0.11s
Early init took 0.11s
Loader init took 0.05s
Loader init took 0.05s
Loading error handling took 2.74s
Loading error handling took 2.74s
Loading script took 30.76s
Loading script took 30.76s
Saving to /storage/emulated/0/Android/data/su.sovietgames.everlastingsummer/files/saves
Loading save slot metadata. took 0.01s
Loading save slot metadata. took 0.01s
Loading persistent took 0.00s
Loading persistent took 0.00s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Set script version to: (7, 0, 0)

Traceback (most recent call last):
  File "main.py", line 198, in <module>
    main()
  File "main.py", line 195, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "/data/user/0/su.sovietgames.everlastingsummer/files/renpy/bootstrap.py", line 333, in bootstrap
    renpy.error.report_exception(e)
  File "/data/user/0/su.sovietgames.everlastingsummer/files/renpy/error.py", line 211, in report_exception
    sys.stdout.write(full.getvalue())
  File "/data/user/0/su.sovietgames.everlastingsummer/files/renpy/log.py", line 227, in write
    self.real_file.write(es) #
  File "<string>", line 19, in write
TypeError: must be string without null bytes, not str
`

**Comment by Dreamtale** [comment]
Well I did some workaround in log.py:
```
        try:
            self.real_file.write(es)
            self.real_file.flush()
        except:
            self.real_file.write("WARNING: ERROR WRITING TO FILE!")
            self.real_file.flush()
```

**Comment by Uzume** [comment]
@Dreamtale Рита Тайнакова, that error comes from here:
- https://github.com/python/cpython/blob/2.7/Python/getargs.c#L925
However, I am not exactly sure what is causing it (clearly some sort of encoding issue). 

Here are some similar issues: 
- weechat/scripts#184
- ipython/ipython#2431

You might get more useful information in your workaround with code like:
```python
        try:
            self.real_file.write(es)
            self.real_file.flush()
        except:
            self.real_file.write("WARNING: ERROR WRITING TO FILE!\n{0}".format(es.replace('\0', '')))
            self.real_file.flush()
```

**Comment by huntertritter** [comment]
This needs fixing cause i can't find a Solution to this Line in the Code. If One of 
you guys help, i'd really appreciate it.

This is the Code.
subObject: Traceback (most recent call last):
  File "C:\noesisv4395\plugins\python\fmt_DBL.py", line 32, in LoadModel
    readObject(bs)
  File "C:\noesisv4395\plugins\python\fmt_DBL.py", line 137, in readObject
    print("subObject:",name, info, bs.getOffset())
TypeError: must be str without null bytes, not str
[fmt_DBL.zip](https://github.com/renpy/renpy/files/11739086/fmt_DBL.zip)
