### ISSUE TITLE
Exception if callback relies on default

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1690]
For code
```
default foo = []
init python:
    def bar():
        for i in foo:
            i()
    config.start_interact_callbacks.append(bar)

label start:
    return

label start:
    return
```
We get:
```
While handling exception:
Traceback (most recent call last):
  File "C:\renpy\renpy\display\error.py", line 186, in report_parse_errors
    error_fn=error_fn,
  File "C:\renpy\renpy\game.py", line 281, in invoke_in_new_context
    return callable(*args, **kwargs)
  File "C:\renpy\renpy\display\error.py", line 44, in call_exception_screen
    return renpy.ui.interact(mouse="screen", type="screen", suppress_overlay=True, suppress_underlay=True)
  File "C:\renpy\renpy\ui.py", line 289, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\renpy\renpy\display\core.py", line 2665, in interact
    i()
  File "game/script.rpy", line 4, in bar
    for i in foo:
NameError: global name 'foo' is not defined

Full traceback:
  File "C:\renpy\renpy\bootstrap.py", line 313, in bootstrap
    renpy.main.main()
  File "C:\renpy\renpy\main.py", line 440, in main
    renpy.game.script.report_duplicate_labels()
  File "C:\renpy\renpy\script.py", line 907, in report_duplicate_labels
    if renpy.parser.report_parse_errors():
  File "C:\renpy\renpy\parser.py", line 2787, in report_parse_errors
    renpy.display.error.report_parse_errors(full_text, error_fn)
  File "C:\renpy\renpy\display\error.py", line 186, in report_parse_errors
    error_fn=error_fn,
  File "C:\renpy\renpy\game.py", line 281, in invoke_in_new_context
    return callable(*args, **kwargs)
  File "C:\renpy\renpy\display\error.py", line 44, in call_exception_screen
    return renpy.ui.interact(mouse="screen", type="screen", suppress_overlay=True, suppress_underlay=True)
  File "C:\renpy\renpy\ui.py", line 289, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\renpy\renpy\display\core.py", line 2665, in interact
    i()
  File "game/script.rpy", line 4, in bar
    for i in foo:
NameError: global name 'foo' is not defined

After initialization, but before game start.
  File "game/script.rpy", line 4, in bar
    for i in foo:
NameError: global name 'foo' is not defined
```
The error occurs due to the fact that report_duplicate_labels executed before execute_default_statement.
But renpy.display.errors are based on renpy.ui.interact

**Comment by renpytom** [comment]
I don't think this is fixable in the general case. If you have a powerful callback like a config.start_interact_callback, then I think it's up to you to make sure that it's able to deal with failures like this one. 

I realize this isn't very satisfying, but it's kind of a problem with how flexible Ren'Py is. I don't think I could necessarily find and catch everything that could be called with Ren'Py in an error state like this. And running the defaults won't work, either, as the defaults might requires proper initialization in order to work.
