### ISSUE TITLE
Unable to build for Android on Windows

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1919]
I just updated recently from 7.2.2 to 7.3.2 and at 7.2.2 the Android build worked correctly.  However right now it's failing.  Even reverting back to 7.2.2 shows the same error.

```
Ren'Py 7.3.2.320

I'm compiling a short test program, to see if you have a working JDK on your system.



Traceback (most recent call last):
  File "game/mobilebuild.rpy", line 197, in call
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/subprocess.py", line 710, in __init__
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/subprocess.py", line 958, in _execute_child
WindowsError: [Error 5] Access is denied

I was unable to use javac to compile a test file. If you haven't installed the Java Development Kit yet, please download it from:

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

The JDK is different from the JRE, so it's possible you have Java without having the JDK. Without a working JDK, I can't continue.
```

FWIW here's the fullversion of Java I have
```
C:\opt\renpy>javac -fullversion
javac full version "1.8.0_211-b12"

C:\opt\renpy>java -fullversion
java full version "1.8.0_211-b12"
```

I also checked in the console os.getEnv("JAVA_HOME") and it returns the values I expect 

The thing is I am not sure what file it is trying to access.  I also tried running as admin with no luck.

**Comment by trajano** [comment]
This was caused by having the JAVA_HOME wrapped in quotes (due to a space in `Program Files`) so use `Progra~1`
