### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by OverPie** [renpy/renpy#2161]
trying to build renpy by https://github.com/renpy/renpy/blob/master/README.rst
have error at: ```$ python -O renpy.py```
traceback:
```python
Traceback (most recent call last):
  File "renpy.py", line 199, in <module>
    main()
  File "renpy.py", line 196, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "/home/unix/sources/renpy-7.3.5-source/renpy/bootstrap.py", line 291, in bootstrap
    renpy.import_all()
  File "/home/unix/sources/renpy-7.3.5-source/renpy/__init__.py", line 368, in import_all
    import renpy.pyanalysis
  File "/home/unix/sources/renpy-7.3.5-source/renpy/pyanalysis.py", line 28, in <module>
    from renpy.python import py_compile
  File "/home/unix/sources/renpy-7.3.5-source/renpy/python.py", line 88, in <module>
    from renpy.pydict import DictItems, find_changes
ImportError: No module named pydict
```
distribution: alpinelinux

**Comment by uyjulian** [comment]
Install pydict from pip

**Comment by renpytom** [comment]
renpy.pydict isn't in a nightly yet... I'll work to get it built in the next few days.

**Comment by OverPie** [comment]
> Install pydict from pip

didn`t help

**Comment by OverPie** [comment]
@renpytom i have ```./renpy/pydict.pyx``` file

**Comment by OverPie** [comment]
just rebuild renpy with clang and see the result
