### ISSUE TITLE
Ren'Py 7.4 Windows encoding problem.

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#2205]
Nightly builds do not run on Windows correctly rely to encoding
```
Traceback (most recent call last):
  File "renpy.py", line 200, in <module>
    main()
  File "renpy.py", line 196, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "renpy/bootstrap.py", line 163, in bootstrap
    print("test")
LookupError: unknown encoding: cp65001
```
And it can't even write an error in traceback.txt because of it.

**Comment by Andykl** [comment]
Also, it writes spurious newlines in log.txt
Raw data are ```LINE\r\r\n```

**Comment by Andykl** [comment]
When opening with a console it gives
```
...
  File "renpy/display/core.py", line 2261, in set_mode
    if draw.init(virtual_size):
  File "gl2draw.pyx", line 294, in renpy.gl2.gl2draw.GL2Draw.init
  File "renpy/log.py", line 233, in write
    self.real_file.write(s)
LookupError: unknown encoding: cp65001
```

**Comment by renpytom** [comment]
Can you take a look at tomorrow's nightly? I'm thinking that renpy/renpy-build@5c6bb92 might have fixed it, and if not, I'll look into it further.

**Comment by Andykl** [comment]
Nope. Still fall with
```
Full traceback:
  File "launcher/game/editor.rpyc", line 27, in script
    ��'�8γYNl��D����9~"����� ��0w���t*�ψͅҪ�=�7�#kQs��"7�-���Ň�,Q��Ŷ�jl�M��&����K�ql��UC�������YZ=aK�n��wgi�ݲ�xEA�:RZ���f����(�#n���{J���x���w� {��9x�U���E�-㵑�܍`eN<��
  File "renpy/ast.py", line 908, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2102, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/editor.rpy", line 303, in <module>
  File "game/editor.rpy", line 277, in fancy_activate_editor
  File "renpy/editor.py", line 129, in init
    with open(path, "r") as f:

LookupError: unknown encoding: cp1251
```

**Comment by rdurfee** [comment]
I see a similar error when trying to add the "atom" folder to the Renpy 7.4 SDK folder. If you copy the atom folder to 7.4, the Launcher fails to launch.

```
While running game code:
  File "game/editor.rpy", line 303, in <module>
  File "game/editor.rpy", line 277, in fancy_activate_editor
LookupError: unknown encoding: cp1252
```

**Comment by renpytom** [comment]
Hopefully, this is fixed in the 6-13 nightly.

**Comment by Andykl** [comment]
Yes, it finally fixed.
