### ISSUE TITLE
Renpy nightly-2020-06-11-d45a30cd

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#2237]
Renpy 7.4 does not run on windows, it generates a log.txt and the traceback is generated empty

log.txt
```
Thu Jun 11 22:50:19 2020

Windows-10-10.0.18362

Ren'Py 7.4.0.478

 



Bootstrap to the start of init.init took 0.86s

Early init took 0.01s

Loader init took 0.04s

Loading error handling took 0.55s

Loading script took 7.22s

Loading save slot metadata. took 0.03s

Loading persistent took 0.00s

Importing _renpysteam: ImportError('No module named _renpysteam',)

 - Init at launcher/game/web.rpyc:26 took 0.52958 s.



Full traceback:

  File "launcher/game/editor.rpyc", line 27, in script

    �M�3����\

  File "renpy/ast.py", line 908, in execute

    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)

  File "renpy/python.py", line 2102, in py_exec_bytecode

    exec(bytecode, globals, locals)

  File "game/editor.rpy", line 303, in <module>

  File "game/editor.rpy", line 277, in fancy_activate_editor

  File "renpy/editor.py", line 129, in init

    with open(path, "r") as f:

LookupError: unknown encoding: cp932



While running game code:

  File "game/editor.rpy", line 303, in <module>

  File "game/editor.rpy", line 277, in fancy_activate_editor

LookupError: unknown encoding: cp932



Full traceback:

  File "renpy/bootstrap.py", line 324, in bootstrap

    renpy.main.main()

  File "renpy/main.py", line 496, in main

    renpy.game.context().run(node)

  File "launcher/game/editor.rpyc", line 27, in script

    �M�3����\

  File "renpy/error.py", line 240, in report_exception

    return simple, full, traceback_fn

UnboundLocalError: local variable 'traceback_fn' referenced before assignment



While running game code:

UnboundLocalError: local variable 'traceback_fn' referenced before assignment

Traceback (most recent call last):

  File "C:\Users\neyun\Desktop\renpy-nightly-2020-06-11-d45a30cd-sdk\renpy.py", line 200, in <module>

    main()

  File "C:\Users\neyun\Desktop\renpy-nightly-2020-06-11-d45a30cd-sdk\renpy.py", line 196, in main

    renpy.bootstrap.bootstrap(renpy_base)

  File "renpy/bootstrap.py", line 351, in bootstrap

    renpy.error.report_exception(e)

  File "renpy/error.py", line 240, in report_exception

    return simple, full, traceback_fn

UnboundLocalError: local variable 'traceback_fn' referenced before assignment
```

**Comment by renpytom** [comment]
Can you try the 6-12 version? I believe it should fix this.

**Comment by Neyunse** [comment]
> Can you try the 6-12 version? I believe it should fix this.

```
Fri Jun 12 16:59:23 2020

Windows-10-10.0.18362

Ren'Py 7.4.0.479

 



Bootstrap to the start of init.init took 0.89s

Early init took 0.00s

Loader init took 0.04s

Loading error handling took 0.62s

Loading script took 8.61s

Loading save slot metadata. took 0.06s

Loading persistent took 0.00s

Importing _renpysteam: ImportError('No module named _renpysteam',)

 - Init at launcher/game/web.rpyc:26 took 0.52160 s.



Full traceback:

  File "launcher/game/editor.rpyc", line 27, in script

     ����})��`��,�`_��

  File "renpy/ast.py", line 908, in execute

    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)

  File "renpy/python.py", line 2102, in py_exec_bytecode

    exec(bytecode, globals, locals)

  File "game/editor.rpy", line 303, in <module>

  File "game/editor.rpy", line 277, in fancy_activate_editor

  File "renpy/editor.py", line 129, in init

    with open(path, "r") as f:

LookupError: unknown encoding: cp932



While running game code:

  File "game/editor.rpy", line 303, in <module>

  File "game/editor.rpy", line 277, in fancy_activate_editor

LookupError: unknown encoding: cp932



Full traceback:

  File "renpy/bootstrap.py", line 324, in bootstrap

    renpy.main.main()

  File "renpy/main.py", line 496, in main

    renpy.game.context().run(node)

  File "launcher/game/editor.rpyc", line 27, in script

     ����})��`��,�`_��

  File "renpy/error.py", line 240, in report_exception

    return simple, full, traceback_fn

UnboundLocalError: local variable 'traceback_fn' referenced before assignment



While running game code:

UnboundLocalError: local variable 'traceback_fn' referenced before assignment

Traceback (most recent call last):

  File "C:\Users\neyun\Desktop\renpy-nightly-2020-06-12-530b29fb-sdk\renpy.py", line 200, in <module>

    main()

  File "C:\Users\neyun\Desktop\renpy-nightly-2020-06-12-530b29fb-sdk\renpy.py", line 196, in main

    renpy.bootstrap.bootstrap(renpy_base)

  File "renpy/bootstrap.py", line 351, in bootstrap

    renpy.error.report_exception(e)

  File "renpy/error.py", line 240, in report_exception

    return simple, full, traceback_fn

UnboundLocalError: local variable 'traceback_fn' referenced before assignment
```

**Comment by rdurfee** [comment]
This error in editor.rpyc seems to happen if you have an editor installed in the RenPy sdk folder, for example you unzip the Atom folder into the sdk folder.

If you delete the folder, the Launcher will open ... but nothing really works because you will get additional encoding errors.

**Comment by renpytom** [comment]
Thanks for that. I'm pretty sure I was able to track it down to locale.getpreferredencoding() returning an encoding that the distribution of Ren'Py doesn't support. A monkeypatch later, and it should be returning the right encoding in 6-13's build.
