### ISSUE TITLE
Segmentation fault when loading WebP images on armv7l

### ISSUE THREAD

**Issue by jackmcbarn** [renpy/renpy#2620]
When I try to load a WebP image on a Linux armv7l system, using Ren'Py 7.4.1 and the extra files from https://www.renpy.org/dl/7.4.1/renpy-7.4.1-raspi.tar.bz2, Ren'Py segfaults. It happens with every WebP image I've tried. It works fine if I run on x86_64 instead of armv7l, or if I use a PNG image in place of the WebP image. Nothing relevant appears in log.txt. Here's a backtrace from the core dump file, although it doesn't look very useful:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xb67da73c in ?? ()
   from /home/pi/renpy-7.4.1-sdk/lib/linux-armv7l/librenpython.so
[Current thread is 1 (Thread 0xb6fa0400 (LWP 1379))]
(gdb) bt
#0  0xb67da73c in ?? ()
   from /home/pi/renpy-7.4.1-sdk/lib/linux-armv7l/librenpython.so
#1  0x022d9aa0 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

**Comment by jackmcbarn** [comment]
For the record: I tried on the same device in 64-bit mode with arm64 builds (see my PRs #2418 and renpy/renpy-build#8) and it works fine that way, so this problem appears specific to 32-bit ARM.
