### ISSUE TITLE
Collapse repeated lines in tracebacks

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#3068]
Most likely it is broken recursion, but also it is about exception where was script call recursion.
Python 3 do such traceback for recursive call
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in f
  File "<stdin>", line 1, in f
  File "<stdin>", line 1, in f
  [Previous line repeated 996 more times]
```

**Comment by GiovanH** [comment]
This appears to already be the implemented behavior:
![image](https://github.com/user-attachments/assets/8a08be80-32d9-4e83-ba03-5428b6bffc4b)

**Comment by Andykl** [comment]
This is fully implemented in 8.4
