### ISSUE TITLE
[Ren'Py 8 01-05 nightly] Update/Requests do not work.

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3217]
In the latest Renpy 8 nightly when pressing the update button and when my game is trying to do a http request (works in 7.4.11) this error appears:

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Desktop\\renpy-8-nightly-2022-01-05-f8869d098-sdk\\lib\\python3.9\\certifi\\cacert.pem'

**Comment by renpytom** [comment]
Requests should be fixed in the next nightly, though I haven't tested the update button.

**Comment by raspberry-soft** [comment]
Hi Tom. In the latest nightly (01-11) the game now does not crash when request is used, but when trying to update the launcher it gives this error
![2022-01-11 15_12_10-Ren'Py Launcher](https://user-images.githubusercontent.com/87047775/149015278-482b0b05-7d65-4b59-baba-4cfef3bf1c52.png)

And when trying to use requests in my game it gives me this error:

```
Traceback (most recent call last):
  File "/home/tom/ab/nightly-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 589, in urlopen
  File "/home/tom/ab/nightly-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 251, in _get_conn
  File "/home/tom/ab/nightly-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 827, in _new_conn
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
```

Additionally, this other error occurs:

```
Saving shaders to 'D:\\Desktop\\Otros\\renpy-7.4.4-sdk\\My_Project/game\\cache/shaders.txt':
Traceback (most recent call last):
  File "D:\Desktop\renpy-8-nightly-2022-01-11-aab2fb78a-sdk\renpy\bootstrap.py", line 314, in bootstrap
    sys.exit(exit_status)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\renpy-8-nightly-2022-01-11-aab2fb78a-sdk\renpy\gl2\gl2shadercache.py", line 321, in save
    f.write(u" ".join(i) + "\r\n")
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by Gouvernathor** [comment]
This is two different problems. Can you give a piece of renpy code triggering the second one ?

**Comment by raspberry-soft** [comment]
As I am aware, the last issue happens with every game, even new ones (created with 7, as 8 cannot create new projects yet). It's reported at the end of the log file, in the "Initializing gl2 renderer" section.

**Comment by renpytom** [comment]
I believe this has all been fixed.

**Comment by raspberry-soft** [comment]
Yes it works! Thank you!
