### ISSUE TITLE
Help with error when building android package in newly downloaded ren'py & rapt

### ISSUE THREAD

**Issue by Billarin** [renpy/renpy#3372]
`Ren'Py 7.4.11.2266

Updating project.

Creating assets directory.

Packaging internal data.

I'm using Gradle to build the package.
Could not unzip C:\Users\ASUS\.gradle\wrapper\dists\gradle-6.1.1-bin\4i3ntwqiazourd86epxcz427c\gradle-6.1.1-bin.zip to C:\Users\ASUS\.gradle\wrapper\dists\gradle-6.1.1-bin\4i3ntwqiazourd86epxcz427c.
Reason: error in opening zip file
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:235)
	at org.gradle.wrapper.Install.access$900(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:81)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Picked up _JAVA_OPTIONS: -Xmx4096M

The build seems to have failed.`

I used to have ren'py and rapt that work perfectly before but I accidentally deleted it and then I downloaded Ren'py again along with rapt intending to port a game to android but above error appeared. Can anyone help me? I don't know why only gradle zip file cannot be extracted when the key zip file can be extracted perfectly fine.

**Comment by renpytom** [comment]
Could you check the Path on your system? ASUS.gradle has nothing to do with Ren'Py, and so it makes it seem like you might have a second copy of Gradle on your system that's interfering.

**Comment by Billarin** [comment]
> Could you check the Path on your system? ASUS.gradle has nothing to do with Ren'Py, and so it makes it seem like you might have a second copy of Gradle on your system that's interfering.

Can you perhaps tell me how to do that step by step? I am really sorry but I am a beginner at this so I am quite confused since I am porting perfectly fine before I removed my previous ren'py.

**Comment by renpytom** [comment]
Hm...

Can you try running the "set" command, to see what it shows?

**Comment by Billarin** [comment]
I have android studio? could that be the problem? should I uninstall it?

**Comment by Billarin** [comment]
> Hm...
> 
> Can you try running the "set" command, to see what it shows?

`ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\ASUS\AppData\Roaming
asl.log=Destination=file
CM2014DIR=C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-GFBBCQQ
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\ASUS
ILBDIR=C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\
JD2_HOME=C:\Users\ASUS\AppData\Local\JDownloader 2.0
LOCALAPPDATA=C:\Users\ASUS\AppData\Local
LOGONSERVER=\\DESKTOP-GFBBCQQ
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\ASUS\OneDrive
OneDriveConsumer=C:\Users\ASUS\OneDrive
OS=Windows_NT
Path=C:\Program Files\Common Files\Oracle\Java\javapath;D:\Program Files\Ruby31-x64\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\CineForm\Tools;C:\Program Files (x86)\GoPro\Tools;C:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\System32\OpenSSH\;C:\Users\ASUS\AppData\Local\Microsoft\WindowsApps;C:\adb;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Program Files\Calibre2\;D:\Program Files\IBM\JRE\bin;D:\Program Files\Ruby31-x64\bin;C:\Users\ASUS\AppData\Local\Microsoft\WindowsApps
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.RB;.RBW
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Temp
TMP=D:\Program Files\Temp
TMPDIR=C:\Users\Public\Documents\Wondershare\CreatorTemp
USERDOMAIN=DESKTOP-GFBBCQQ
USERDOMAIN_ROAMINGPROFILE=DESKTOP-GFBBCQQ
USERNAME=ASUS
USERPROFILE=C:\Users\ASUS
windir=C:\WINDOWS
_JAVA_OPTIONS=-Xmx4096M`

**Comment by Andykl** [comment]
I believe it is a moot.
