### ISSUE TITLE
Zsync doesn't support files larger than 2GB in size.

### ISSUE THREAD

**Issue by Victorius-Astral** [renpy/renpy#3496]
Hey, 

I've tried to use WebUpdater with http, but the result was that it tried to download the whole game. The game is 2.6GB, the patch with all scripts + new images is 160MB, and it was not even halfway done with 1GB downloaded.

I tried with this button:
`textbutton _("Check for Updates") action updater.Update(url = "http://update.astrallust.com/public/updates.json", restart = True, confirm = True, patch = True) yalign 0.05`

The game itself doesn't use .rpa archives, everything is loose. Maybe I misunderstood how it should work, but the docs say it'll try to download just the different files. To make sure I made 0.2.2b, then change the version number (so changed one script file), added some images, and compiled 0.2.3 updates. The update.astrallust.com is just a single placeholder page with nothing besides the files. 

Renpy 7.5.0.22051201n

![Screenshot_2](https://user-images.githubusercontent.com/78815540/168098489-f464662d-345b-4199-a205-010a74262963.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/78815540/168098492-315ea01a-1145-4c89-ab7e-4203d70f11cd.jpg)

**Comment by Victorius-Astral** [comment]
Log might help:

running ['C:/Users/Victorius/Desktop/AstralLust-0.2.2b-pc\\lib\\py2-windows-i686\\zsync.exe', '-o', 'C:\\Users\\Victorius\\Desktop\\AstralLust-0.2.2b-pc\\update\\pc.update.new', '-k', 'C:\\Users\\Victorius\\Desktop\\AstralLust-0.2.2b-pc\\update\\pc.zsync', '-i', 'C:\\Users\\Victorius\\Desktop\\AstralLust-0.2.2b-pc\\update\\pc.update', 'http://btc.i586.pl/victorius/AstralLust-0.2.2c-pc.zsync']
bad offset -2147371750, not in z-map
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
running ['C:/Users/Victorius/Desktop/AstralLust-0.2.2b-pc\\lib\\py2-windows-i686\\zsync.exe', '-o', 'C:\\Users\\Victorius\\Desktop\\AstralLust-0.2.2b-pc\\update\\pc.update.new', 'http://btc.i586.pl/victorius/AstralLust-0.2.2c-pc.zsync']
rename: Permission denied
Unable to back up old file C:\Users\Victorius\Desktop\AstralLust-0.2.2b-pc\update\pc.update.new - completed download left in C:\Users\Victorius\Desktop\AstralLust-0.2.2b-pc\update\pc.update.new.part
could not rename file \\?\C:\Users\Victorius\Desktop\AstralLust-0.2.2b-pc\game\audio\atmosphere_dark.mp3could not rename file \\?\C:\Users\Victorius\Desktop\AstralLust-0.2.2b-pc\game\fonts\Commissioner-Regular.ttfcould not rename file \\?\C:\Users\Victorius\Desktop\AstralLust-0.2.2b-pc\game\fonts\FrederickatheGreat-Regular.ttfcould not rename file \\?\C:\Users\Victorius\Desktop\AstralLust-0.2.2b-pc\renpy\common\DejaVuSans.ttfR \\?\C:\Users\Victorius\Desktop\AstralLust-0.2.2b-pc\game\audio\atmosphere_dark.mp3Traceback (most recent call last):
  File "renpy/common/00updater.rpy", line 121, in process_deferred
    process_deferred_line(l)
  File "renpy/common/00updater.rpy", line 97, in process_deferred_line
    raise Exception("Bad command.")
Exception: Bad command.
R \\?\C:\Users\Victorius\Desktop\AstralLust-0.2.2b-pc\game\fonts\Commissioner-Regular.ttfTraceback (most recent call last):
  File "renpy/common/00updater.rpy", line 121, in process_deferred
    process_deferred_line(l)
  File "renpy/common/00updater.rpy", line 87, in process_deferred_line
    os.unlink(fn)
WindowsError: [Error 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces: u'\\\\?\\C:\\Users\\Victorius\\Desktop\\AstralLust-0.2.2b-pc\\game\\fonts\\Commissioner-Regular.ttf'
Traceback (most recent call last):
  File "renpy/common/00updater.rpy", line 121, in process_deferred
    process_deferred_line(l)
  File "renpy/common/00updater.rpy", line 97, in process_deferred_line
    raise Exception("Bad command.")
Exception: Bad command.
R \\?\C:\Users\Victorius\Desktop\AstralLust-0.2.2b-pc\game\fonts\FrederickatheGreat-Regular.ttfTraceback (most recent call last):
  File "renpy/common/00updater.rpy", line 121, in process_deferred
    process_deferred_line(l)
  File "renpy/common/00updater.rpy", line 87, in process_deferred_line
    os.unlink(fn)
WindowsError: [Error 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces: u'\\\\?\\C:\\Users\\Victorius\\Desktop\\AstralLust-0.2.2b-pc\\game\\fonts\\FrederickatheGreat-Regular.ttf'
Traceback (most recent call last):
  File "renpy/common/00updater.rpy", line 121, in process_deferred
    process_deferred_line(l)
  File "renpy/common/00updater.rpy", line 97, in process_deferred_line
    raise Exception("Bad command.")
Exception: Bad command.
R \\?\C:\Users\Victorius\Desktop\AstralLust-0.2.2b-pc\renpy\common\DejaVuSans.ttfTraceback (most recent call last):
  File "renpy/common/00updater.rpy", line 121, in process_deferred
    process_deferred_line(l)
  File "renpy/common/00updater.rpy", line 87, in process_deferred_line
    os.unlink(fn)
WindowsError: [Error 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces: u'\\\\?\\C:\\Users\\Victorius\\Desktop\\AstralLust-0.2.2b-pc\\renpy\\common\\DejaVuSans.ttf'
Traceback (most recent call last):
  File "renpy/common/00updater.rpy", line 121, in process_deferred
    process_deferred_line(l)
  File "renpy/common/00updater.rpy", line 97, in process_deferred_line
    raise Exception("Bad command.")
Exception: Bad command.
