### ISSUE TITLE
Web Updater: TypeError

### ISSUE THREAD

**Issue by loafylemon** [renpy/renpy#3641]
Windows 11
Ren'py 7.5.0.22061002n

When I try to patch the game via the built-in web updater, I get a TypeError (posted below).
The update server is set up in http mode, and all necessary files are located in the public directory and fully accessible.

Am I doing something wrong?

Server URL example:

```http://127.0.0.1/updates.json```

Server Files:
```
WTS-1.43.1-win.sums       
WTS-1.43.1-win.update.json  
updates.json
WTS-1.43.1-win.update.gz  
WTS-1.43.1-win.zsync
```
Updates.json:
```json
{
  "win": {
    "sums_url": "WTS-1.43.1-win.sums", 
    "version": "e3e1c989903538f76f8f48df48a31ed9e517b082531301c1fbe8c6d35d29b6d4", 
    "zsync_url": "WTS-1.43.1-win.zsync", 
    "json_url": "WTS-1.43.1-win.update.json", 
    "pretty_version": "1.43.1", 
    "sums_size": 46268, 
    "digest": "822c9e57de5e884a50855022371e9be1e11b3a2eb861ef374a67bd40d422f43c"
  }
}
```
Traceback:
```
Traceback (most recent call last):
  File "renpy/common/00updater.rpy", line 357, in run
    self.update()
  File "renpy/common/00updater.rpy", line 471, in update
    self.download(i, standalone=True)
  File "renpy/common/00updater.rpy", line 930, in download
    f = urlopen(urlparse.urljoin(self.url, self.updates[module]["sums_url"]))
  File "/home/tom/ab/nightly-build/tmp/install.linux-x86_64/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 418, in urljoin
  File "/home/tom/ab/nightly-build/tmp/install.linux-x86_64/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 115, in _coerce_args
TypeError: Cannot mix str and non-str arguments
```

**Comment by renpytom** [comment]
Nice catch. I was able to repeat this, so I'm fairly confident in the fix.

**Comment by loafylemon** [comment]
I gave it another shot and can confirm that the problem has been resolved. Thank you very much!
