### ISSUE TITLE
Console output preference bug

### ISSUE THREAD

**Issue by loafylemon** [renpy/renpy#3936]
Windows 11 (21H2)
Ren'py 7.5.3.22083102 (Prerelease)

The project won't start if `Console output` is enabled in Ren'py preferences.

```
Traceback (most recent call last):
  File "renpy/log.py", line 140, in open
    self.write("%s", time.ctime())
  File "renpy/log.py", line 177, in write
    self.file.flush() # type: ignore
IOError: [Errno 9] Bad file descriptor

Full traceback:
  File "renpy/bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 610, in main
    renpy.dump.dump(False)
  File "renpy/dump.py", line 253, in dump
    with open(new, "wb") as f:
IOError: [Errno 2] No such file or directory: u'C:\\Projects\\GIT\\New Project\\game\\saves\\navigation.json.new'

After initialization, but before game start.
IOError: [Errno 2] No such file or directory: u'C:\\Projects\\GIT\\New Project\\game\\saves\\navigation.json.new'

[process exited with code 1 (0x00000001)]
```

**Comment by Gouvernathor** [comment]
Likely fixed by 1fa440f
