### ISSUE TITLE
Multiple Users reporting freezing on Steam Deck

### ISSUE THREAD

**Issue by fishghost42** [renpy/renpy#3978]
Multiple users have been reporting freezing on Steam Deck.

It seems like one of them found a work around by force changing the render option: https://twitter.com/melisenx/status/1570632605254701058/photo/1

Worth noting I can't replicate the issue on my own Deck, nor can the majority of our players with decks, but the render change seems to have fixed the issue for multiple people (and hasn't fixed it for others.) Possibly worth making it so Ren'py automatically selects that rendering option on startup if the device in question is a Deck?

Here's a link to the thread where people have been reporting issues: https://steamcommunity.com/app/1609230/discussions/0/5595176692467381955/?tscn=1663421564

**Comment by perverteer** [comment]
I've had several users with Steam Decks reporting the same issue. One of them included a log. Like fishghost42, I can't replicate the issue on my own Steam Deck. The relevant part of the log seems to be this:

```
controller: u'03000000de280000ff11000001000000' u'Steam Virtual Gamepad' 1
controller: u'03000000de280000ff11000001000000' u'Steam Virtual Gamepad' 1
Traceback (most recent call last):
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/lib/py2-linux-x86_64/../../TFTUV.py", line 251, in <module>
    main()
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/lib/py2-linux-x86_64/../../TFTUV.py", line 247, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/main.py", line 660, in main
    run(restart)
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/main.py", line 146, in run
    renpy.execution.run_context(True)
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/execution.py", line 938, in run_context
    context.run()
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/execution.py", line 581, in run
    node.execute()
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/character.py", line 1266, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/character.py", line 930, in do_display
    **display_args)
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/character.py", line 666, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/display/core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "/run/media/mmcblk0p1/steamapps/common/Tales From The Unending Void/renpy/display/core.py", line 3873, in interact_core
    if i():
  File "renpy/common/00steam.rpy", line 314, in overlay_needs_present
    return steamapi.SteamUtils().BOverlayNeedsPresent()
  File "/home/tom/ab/renpy-build/tmp/py2/steam/steamapi.py", line 5287, in BOverlayNeedsPresent
KeyboardInterrupt
```

The entire log: [log.txt](https://github.com/renpy/renpy/files/9613880/log.txt)

**Comment by renpytom** [comment]
I've just filed an issue with SteamWorks support. I'll see what they have to say.

**Comment by fishghost42** [comment]
Was there a response from SteamWorks? Getting more messages from users.

**Comment by fishghost42** [comment]
Hi there! Looks like some of our players sleuthed it out and wrote a temporary fix! I don't know if this would be helpful for implementing an official fix

https://steamcommunity.com/app/1609230/discussions/0/3488626756880789876/?ctp=2
