### ISSUE TITLE
ERROR [PORT]

### ISSUE THREAD

**Issue by mxa23** [renpy/renpy#4068]
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\USUARIO-I\.gradle\wrapper\dists\gradle-6.1.1-bin\4i3ntwqiazourd86epxcz427c\gradle-6.1.1-bin.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

**Comment by renpytom** [comment]
This is unlikely to be a Ren'Py problem. Please make sure you do not have a slow virus check or other similar program that's causing your computer to malfunction.

**Comment by mxa23** [comment]
I don't think it's some kind of virus, my computer is freshly formatted

**Comment by mxa23** [comment]
Muchas gracias, he conseguido solucionar el error instalando un antivirus.

**Comment by mxa23** [comment]
Thank you very much, I managed to solve the error by installing an antivirus.
