### ISSUE TITLE
Error loading RAPT

### ISSUE THREAD

**Issue by Dante00035** [renpy/renpy#4182]
When loading RAPT in the RenPy launcher, it gives an error, I tried it on different versions, the error is everywhere, on three different computers, including a system with a fresh installed Windows. At the moment there is version 7.4.11.

```
Traceback (most recent call last):
  File "renpy/common/00updater.rpy", line 347, in run
    self.update()
  File "renpy/common/00updater.rpy", line 395, in update
    self.check_updates()
  File "renpy/common/00updater.rpy", line 738, in check_updates
    urlretrieve(self.url + ".sig", fn)
  File "renpy/common/00updater.rpy", line 50, in urlretrieve
    data = requests.get(url).content
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/site-packages/requests/api.py", line 75, in get
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/site-packages/requests/api.py", line 60, in request
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
ConnectionError: HTTPConnectionPool(host='update.renpy.org', port=80): Max retries exceeded with url: /7.4.11/updates.json.sig (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000081ca250>: Failed to establish a new connection: [Errno 10060] \xcf\xee\xef\xfb\xf2\xea\xe0 \xf3\xf1\xf2\xe0\xed\xee\xe2\xe8\xf2\xfc \xf1\xee\xe5\xe4\xe8\xed\xe5\xed\xe8\xe5 \xe1\xfb\xeb\xe0 \xe1\xe5\xe7\xf3\xf1\xef\xe5\xf8\xed\xee\xe9, \xf2.\xea. \xee\xf2 \xe4\xf0\xf3\xe3\xee\xe3\xee \xea\xee\xec\xef\xfc\xfe\xf2\xe5\xf0\xe0 \xe7\xe0 \xf2\xf0\xe5\xe1\xf3\xe5\xec\xee\xe5 \xe2\xf0\xe5\xec\xff \xed\xe5 \xef\xee\xeb\xf3\xf7\xe5\xed \xed\xf3\xe6\xed\xfb\xe9 \xee\xf2\xea\xeb\xe8\xea, \xe8\xeb\xe8 \xe1\xfb\xeb\xee \xf0\xe0\xe7\xee\xf0\xe2\xe0\xed\xee \xf3\xe6\xe5 \xf3\xf1\xf2\xe0\xed\xee\xe2\xeb\xe5\xed\xed\xee\xe5 \xf1\xee\xe5\xe4\xe8\xed\xe5\xed\xe8\xe5 \xe8\xe7-',))

**Comment by renpytom** [comment]
Can you connect to http://update.renpy.org without a proxy? I'm not 100% sure what language your computer uses, but I believe that it is saying it can;'t connect to the update server.

**Comment by renpytom** [comment]
I was able to verify it worked from here. It looks like your computer or network is blocking the connection for some reason.
