### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by AdamSmasher1** [renpy/renpy#4488]
Error when playing video files in the web version

$ renpy.movie_cutscene("movies/my_movie.webm", loops=-1)

Traceback (most recent call last):
renpy-pre.js:119   File "gl2texture.pyx", line 582, in renpy.gl2.gl2texture.GLTexture.__del__
renpy-pre.js:119   File "gl2texture.pyx", line 296, in renpy.gl2.gl2texture.GLTexture.has_mipmaps
renpy-pre.js:119 AttributeError: 'NoneType' object has no attribute 'get'

Ren'Py 8.1.0.23032607+nightly
Browser Chrome 111.0.5563.111

**Comment by AdamSmasher1** [comment]
The error is gone, but the problem remains. The video is playing, but the game cannot continue, it does not go further

**Comment by AdamSmasher1** [comment]
> `self.properties` should probably be set [here](https://github.com/renpy/renpy/blob/77889607f3a81111c77a89ea581852a16ae8cd36/renpy/gl2/gl2texture.pyx#L280) for Web (not sure what it should contain though).

The error is gone, but the problem remains. The video is playing, but the game cannot continue, it does not go further
