### ISSUE TITLE
iOS Issue - "ImportError: cannot import name 'RWops_from_file' from 'pygame_sdl2.rwobject' (built-in)"

### ISSUE THREAD

**Issue by Jennyan868** [renpy/renpy#4741]
Hello,

I'm trying to build an update to my iOS renpy game. When I open the app, I see the renpy splash logo and then a black screen. I then see the following error in my Xcode debugger:

```
2023-06-14 21:08:28.793053-0700 Error143[14589:577144] Traceback (most recent call last):
2023-06-14 21:08:28.793138-0700 Error143[14589:577144]   File "/var/containers/Bundle/Application/580F17DA-59E6-4E59-BCB7-570D5AB8DA0B/Error143.app/base/main.py", line 243, in <module>
2023-06-14 21:08:28.793274-0700 Error143[14589:577144]     main()
2023-06-14 21:08:28.793313-0700 Error143[14589:577144]   File "/var/containers/Bundle/Application/580F17DA-59E6-4E59-BCB7-570D5AB8DA0B/Error143.app/base/main.py", line 239, in main
2023-06-14 21:08:28.793412-0700 Error143[14589:577144]     renpy.bootstrap.bootstrap(renpy_base)
2023-06-14 21:08:28.793445-0700 Error143[14589:577144]   File "renpy/bootstrap.py", line 250, in bootstrap
2023-06-14 21:08:28.793525-0700 Error143[14589:577144]   File "renpy/__init__.py", line 409, in import_all
2023-06-14 21:08:28.793594-0700 Error143[14589:577144]   File "renpy/loader.py", line 37, in <module>
2023-06-14 21:08:28.793668-0700 Error143[14589:577144] ImportError: cannot import name 'RWops_from_file' from 'pygame_sdl2.rwobject' (built-in)
```

I've reverted my code to the previous release and this still happens, so this tells me that either an issue with my Xcode project or the latest renpy release. I was using an older version of xcode and renpy, and got the above error, and then tried updating to Renpy 8.1.1 and Xcode 14.3.1 - and the error still occurs. I couldn't see this error anywhere on google or github so any pointers of what the issue could be would be greatly appreciated. Thank you in advance!

**Comment by renpytom** [comment]
This works for me. You need to re-create your xcode project when changing Ren'Py versions, as the files aren't compatible otherwise.
