### ISSUE TITLE
[doc] import sample code has a problem.

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#4899]
Below is the sample code for importing python modules in renpydoc.

    pip install --target game/python-packages requests

    init python:
        import requests

https://renpy.org/doc/html/python.html#first-and-third-party-python-modules-and-packages

but the result is below.

Traceback (most recent call last):
  File "renpy/common/00console.rpy", line 735, in run
    renpy.python.py_exec(code)
  File "E:\Soft\renpy\renpy\python.py", line 1135, in py_exec
    exec(py_compile(source, 'exec'), store, locals)
  File "<none>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "E:\Soft\renpy\renpy\loader.py", line 1020, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/requests/__init__.py", line 147, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "E:\Soft\renpy\renpy\loader.py", line 1020, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/requests/utils.py", line 63, in <module>
  File "python-packages/certifi/core.py", line 71, in where
  File "/home/tom/ab/nightly-build-fix/tmp/install.linux-x86_64/lib/python3.9/importlib/resources.py", line 161, in path
  File "/home/tom/ab/nightly-build-fix/tmp/install.linux-x86_64/lib/python3.9/importlib/resources.py", line 51, in _get_package
TypeError: 'certifi' is not a package

I am concerned about the "/home/tom" part of the error message. The settings in developer are probably still in release files.

I used ren'py 8.1.2.23080701+nightly and the_question.

**Comment by renpytom** [comment]
I'll pick a different package as the example. Requests is now shipped with Ren'Py, so should just work.
