### ISSUE TITLE
Signature validation for updates downloaded using the Downloader is bypassed sometimes

### ISSUE THREAD

**Issue by do10HM** [renpy/renpy#5386]
Renpy 8.2.0.24012702

I believe there is a race condition where the updater skips signature validation when key.pem has not yet been written to disk. I'm using the Downloader for Large Games on Mobile to download two different games, one tiny (4MB) and the other huge (7GB).

When launching through the ren'py launcher on Windows, both games download and launch. When I check the log file, I do not see the logs at line [997](https://github.com/renpy/renpy/blob/master/renpy/common/00updater.rpy#L997) or [1026](https://github.com/renpy/renpy/blob/master/renpy/common/00updater.rpy#L1026). The same happens when I launch the tiny game through Android.

When I launch the huge game through Android, I see the log:
`Verifying with ECDSA.
Traceback (most recent call last):
  File "renpy/common/00updater.rpy", line 1014, in check_updates
  File "lib/python3.9/ecdsa/keys.py", line 673, in verify
  File "lib/python3.9/ecdsa/keys.py", line 729, in verify_digest
ecdsa.keys.BadSignatureError: Signature verification failed`

I further verified this by adding a log above line [994](https://github.com/renpy/renpy/blob/master/renpy/common/00updater.rpy#L994) to print whether the key exists. In the 3 cases where the game loads, the log says the key does not exist. On the case where the signature is not valid, the key.pem does exist. The key does exist on disk, though, when checked.

Sorry I don't have a sample app for this yet. I wanted to get this issue in before putting in much more time on it as it may already be fixed in a later version.

**Comment by do10HM** [comment]
I have to work but will check back later and provide a sample app if needed!

**Comment by do10HM** [comment]
I tried with the nightly build (8.2.1.24022902+nightly) and I believe it's fixed. I will see what's happening with the larger project after I rebuild it with that launcher.

**Comment by do10HM** [comment]
The huge game gets past signature verification! Now it's just cycling, going through the download loop over and over again. Looking into that next.

**Comment by do10HM** [comment]
Fixed in Ren'Py 8.2.1. Thank you!
