### ISSUE TITLE
Android APK compiled in version 8.3.1 fail to start

### ISSUE THREAD

**Issue by kostek00** [renpy/renpy#5770]
I compiled android universal APK on 8.3.1 but whenever I try to start it it turns off after presplash. I installed it on 2 phones and 4 android emulators (Bluestacks, MSI Player, LD Player and Nox Player). All of them fail to start app. So I have made more tests and compiled game on 8.3.0, 8.2.3 and 7.8.1. All devices and emulators played those versions correctly.

I repeated tests on two more games this time only for 8.3.0 and 8.3.1 to be sure and all games compiled on newest version failed to start.

I downloaded fresh installs of all mentioned versions and extracted to different folders and then I downloaded RAPT for each of them through launcher.

**Comment by renpytom** [comment]
Do you have a logcat of what's happening when it fails to start? Did the games work on 8.3.0?

**Comment by kostek00** [comment]
I don't know how and where to get logcat you would need to point me to correct direction of how to get it. And yes, games are working on 8.3.0.

**Comment by qTich** [comment]
```py
2024-09-09 03:19:07.964  6779-6802  python                  org.renpy.thequestion                I  Opening APK '/data/app/~~5v5HM5ijun_eXmLB5RrcLA==/org.renpy.thequestion-ix7kj8QIHze3ltSNZIoPQQ==/base.apk'
2024-09-09 03:19:07.968  6779-6802  python                  org.renpy.thequestion                I  Traceback (most recent call last):
2024-09-09 03:19:07.968  6779-6802  python                  org.renpy.thequestion                I    File "/data/user/0/org.renpy.thequestion/files/main.py", line 304, in <module>
2024-09-09 03:19:07.968  6779-6802  python                  org.renpy.thequestion                I      main()
2024-09-09 03:19:07.968  6779-6802  python                  org.renpy.thequestion                I    File "/data/user/0/org.renpy.thequestion/files/main.py", line 300, in main
2024-09-09 03:19:07.969  6779-6802  python                  org.renpy.thequestion                I      renpy.bootstrap.bootstrap(renpy_base)
2024-09-09 03:19:07.969  6779-6802  python                  org.renpy.thequestion                I    File "renpy/bootstrap.py", line 321, in bootstrap
2024-09-09 03:19:07.969  6779-6802  python                  org.renpy.thequestion                I    File "renpy/__init__.py", line 406, in import_all
2024-09-09 03:19:07.969  6779-6802  python                  org.renpy.thequestion                I    File "renpy/loader.py", line 76, in <module>
2024-09-09 03:19:07.969  6779-6802  python                  org.renpy.thequestion                I    File "lib/python3.9/android/__init__.py", line 12, in <module>
2024-09-09 03:19:07.969  6779-6802  python                  org.renpy.thequestion                I    File "lib/python3.9/jnius/reflect.py", line 208, in autoclass
2024-09-09 03:19:07.969  6779-6802  python                  org.renpy.thequestion                I    File "jnius_export_func.pxi", line 32, in jnius.jnius.find_javaclass
2024-09-09 03:19:07.969  6779-6802  python                  org.renpy.thequestion                I    File "jnius_export_class.pxi", line 252, in jnius.jnius.JavaClass.__init__
2024-09-09 03:19:07.969  6779-6802  python                  org.renpy.thequestion                I  AttributeError: 'Class' object has no attribute '_JavaClass__cls_storage'
```

Raises on `import android.apk`

**Comment by qTich** [comment]
Perhaps this is related to https://github.com/renpy/renpy-build/commit/8890842f2ff2d34b279598e4d77db135e5516b31 ?

**Comment by renpytom** [comment]
It was due to the release being built with Cython 3 by mistake. I'll be making a new prerelease  soon.
