### ISSUE TITLE
broken builds on master after #5783

### ISSUE THREAD

**Issue by qTich** [renpy/renpy#5797]
#5783 broke builds via `renpy-build` on `master`.

```py
Traceback (most recent call last):
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy.py", line 304, in <module>
    main()
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy.py", line 300, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy/bootstrap.py", line 315, in bootstrap
    renpy.import_all()
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy/__init__.py", line 410, in import_all
    import renpy.parameter
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy/parameter.py", line 29, in <module>
    from renpy.easy import EMPTYMAP
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy/easy.py", line 35, in <module>
    Color = renpy.color.Color
AttributeError: module 'renpy' has no attribute 'color'
```

And

```py
Traceback (most recent call last):
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy.py", line 304, in <module>
    main()
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy.py", line 300, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy/bootstrap.py", line 315, in bootstrap
    renpy.import_all()
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy/__init__.py", line 570, in import_all
    backup = Backup()
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy/__init__.py", line 284, in __init__
    self.backup_module(m)
  File "/home/tichq/Documents/GitHub/renpy-build/renpy/renpy/__init__.py", line 334, in backup_module
    print("Reduce Ex is:", repr(v.__reduce_ex__(pickle.PROTOCOL)))
TypeError: cannot pickle 'mappingproxy' object
```

**Comment by Gouvernathor** [comment]
The second one is weird : I don't really understand why pickling the object is even tried.

**Comment by Andykl** [comment]
RenPy pickles pretty much all its modules dicts after `import_all`, so with `utter_restart` you don't import RenPy again but restore variables from the pickled state. You could add your variable to ignore list, so it is not pickled.
