### ISSUE TITLE
[Linux/NixOS 24.05] No audio when running a Ren'py game

### ISSUE THREAD

**Issue by cattokomo** [renpy/renpy#5821]
The issue affected on any Ren'py games. It occured on NixOS 24.05.

Here's the log for a game I tried playing on:
```
Wed Oct  2 01:31:47 2024
Linux-6.6.48-x86_64-with-glibc2.2.5
Ren'Py 7.4.11.2266
 

Bootstrap to the start of init.init took 0.35s
Early init took 0.02s
Loader init took 0.02s
Loading error handling took 0.09s
Loading script took 3.75s
Loading save slot metadata. took 0.02s
Loading persistent took 0.00s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Set script version to: (7, 4, 11)
Running init code took 0.20s
Loading analysis data took 0.18s
Analyze and compile ATL took 0.13s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.41s
DPI scale factor: 1.000000
Creating interface object took 0.00s
Cleaning stores took 0.00s
Init translation took 0.40s
Build styles took 0.01s
Load screen analysis took 0.15s
Analyze screens took 0.01s
Save screen analysis took 0.00s
Prepare screens took 0.38s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.60s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1366, 768)
swap interval: 1 frames
Fullscreen mode.
Vendor: 'Intel'
Renderer: 'Mesa Intel(R) HD Graphics 400 (BSW)'
Version: '4.6 (Compatibility Profile) Mesa 24.0.7'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1366, 768) drawable=(1366, 768)
Could not open 'cache/shaders.txt':
Maximum texture size: 4096x4096
Traceback (most recent call last):
  File "MoonlightCastle.py", line 198, in <module>
    main()
  File "MoonlightCastle.py", line 194, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/main.py", line 662, in main
    run(restart)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/execution.py", line 922, in run_context
    context.run()
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/execution.py", line 565, in run
    node.execute()
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/character.py", line 1249, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/character.py", line 901, in do_display
    **display_args)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/character.py", line 647, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/display/core.py", line 3839, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "/home/komo/Games/MoonlightCastle-2.07.5-pc/renpy/display/core.py", line 2569, in draw_screen
    renpy.display.draw.draw_screen(surftree)
KeyboardInterrupt
```

**Comment by danac78** [comment]
FYI: The example game log uses Renpy 7.4.11, which is very old and not representative of current builds (8.3/7.8).

**Comment by danac78** [comment]
Have you tried downloading https://renpy.org/latest.html, running the launcher, and playing "The Question" to see if the same thing occurs and getting a log from that?

**Comment by renpytom** [comment]
I'm going to close this, and we can reopen it if it's a problem in a current version.
