### ISSUE TITLE
Support for nearest-neighbor scaling with image-based fonts

### ISSUE THREAD

**Issue by celadonk** [renpy/renpy#5830]
Image-based fonts (bmfont, mudgefont, sfont) currently do not respect `config.nearest_neighbor = True` when the window size is increased, so there is no way to preserve hard pixel edges.

**Comment by renpytom** [comment]
Can you put together a small example game showing this problem?

**Comment by celadonk** [comment]
Absolutely. I've attached it here. Hopefully it does an alright job at communicating the issue.
[bitmap font demo.zip](https://github.com/user-attachments/files/17271455/bitmap.font.demo.zip)

**Comment by kijeEnki** [comment]
It looks like in the latest Ren’Py versions this (and all bitmap fonts) don’t work anymore. Tested on both the stable and the nightly fix.

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script
    e "This is how bitmap fonts look"
  File "renpy/display/render.pyx", line 487, in renpy.display.render.render_screen
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
TypeError: ImageFont.glyphs() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 27, in script
    e "This is how bitmap fonts look"
  File "game/script.rpy", line 27, in script
    e "This is how bitmap fonts look"
  File "renpy/display/render.pyx", line 487, in renpy.display.render.render_screen
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
TypeError: ImageFont.glyphs() takes 2 positional arguments but 3 were given

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 27, in script
    e "This is how bitmap fonts look"
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 965, in execute
    statement_name(stmt_name)
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "renpy/ast.py", line 547, in statement_name
    i(name)
    ~^^^^^^
  File "renpy/common/000window.rpy", line 132, in _window_auto_callback
    _window_show(auto=True)
    ~~~~~~~~~~~~^^^^^^^^^^^
  File "renpy/common/000window.rpy", line 75, in _window_show
    renpy.with_statement(trans)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "renpy/exports/statementexports.py", line 260, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/core.py", line 1579, in do_with
    return self.interact(
           ~~~~~~~~~~~~~^
        trans_pause=True, suppress_overlay=not renpy.config.overlay_during_with, mouse="with", clear=clear
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "renpy/display/core.py", line 2219, in interact
    repeat, rv = self.interact_core(
                 ~~~~~~~~~~~~~~~~~~^
        preloads=preloads,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )  # type: ignore
    ^                
  File "renpy/display/core.py", line 2891, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/core.py", line 1380, in draw_screen
    surftree = renpy.display.render.render_screen(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        root_widget,
        ^^^^^^^^^^^^
        renpy.config.screen_width,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
        renpy.config.screen_height,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "renpy/display/render.pyx", line 487, in renpy.display.render.render_screen
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/layout.py", line 896, in render
    surf = render(child, width, height, cst, cat)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/transition.py", line 375, in render
    top = render(self.new_widget, width, height, st, at)
          ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/layout.py", line 896, in render
    surf = render(child, width, height, cst, cat)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/layout.py", line 896, in render
    surf = render(child, width, height, cst, cat)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/screen.py", line 767, in render
    child = renpy.display.render.render(self.child, w, h, st, at)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/layout.py", line 896, in render
    surf = render(child, width, height, cst, cat)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/layout.py", line 1439, in render
    surf = render(child, width - cxmargin - cxpadding, height - cymargin - cypadding, st, at)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/text/text.py", line 2730, in render
    virtual_layout = Layout(self, width, height, renders, drawable_res=False, size_only=True)
                     ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/text/text.py", line 820, in __init__
    seg_glyphs, rtl = self.glyphs_paragraph(p, order)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "renpy/text/text.py", line 1673, in glyphs_paragraph
    rv.append((ts, ts.glyphs(s[offset:], self, l)))
                   ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^  
  File "renpy/text/text.py", line 372, in glyphs
    rv = fo.glyphs(s, level)
         ~~~~~~~~~^^^^^^^^^^
TypeError: ImageFont.glyphs() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "renpy/bootstrap.py", line 376, in bootstrap
    renpy.main.main()
    ~~~~~~~~~~~~~~~^^
  File "renpy/main.py", line 614, in main
    run(restart)
    ~~~^^^^^^^^^
  File "renpy/main.py", line 137, in run
    renpy.execution.run_context(True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "renpy/execution.py", line 1022, in run_context
    context.run()
    ~~~~~~~~~~~^^
  File "game/script.rpy", line 27, in script
    e "This is how bitmap fonts look"
  File "game/script.rpy", line 27, in script
    e "This is how bitmap fonts look"
  File "renpy/display/error.py", line 135, in report_exception
    renpy.game.invoke_in_new_context(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        call_exception_screen,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        ignore_action=ignore_action,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "renpy/game.py", line 301, in invoke_in_new_context
    return callable(*args, **kwargs)
           ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "renpy/display/error.py", line 44, in call_exception_screen
    return renpy.ui.interact(mouse="screen", type="screen", suppress_overlay=True, suppress_underlay=True)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ui.py", line 304, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/core.py", line 2219, in interact
    repeat, rv = self.interact_core(
                 ~~~~~~~~~~~~~~~~~~^
        preloads=preloads,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )  # type: ignore
    ^                
  File "renpy/display/core.py", line 2891, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/core.py", line 1380, in draw_screen
    surftree = renpy.display.render.render_screen(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        root_widget,
        ^^^^^^^^^^^^
        renpy.config.screen_width,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
        renpy.config.screen_height,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "renpy/display/render.pyx", line 487, in renpy.display.render.render_screen
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/layout.py", line 896, in render
    surf = render(child, width, height, cst, cat)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/layout.py", line 896, in render
    surf = render(child, width, height, cst, cat)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/layout.py", line 896, in render
    surf = render(child, width, height, cst, cat)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/screen.py", line 767, in render
    child = renpy.display.render.render(self.child, w, h, st, at)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/layout.py", line 896, in render
    surf = render(child, width, height, cst, cat)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/display/layout.py", line 1439, in render
    surf = render(child, width - cxmargin - cxpadding, height - cymargin - cypadding, st, at)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/render.pyx", line 170, in renpy.display.render.render
  File "renpy/display/render.pyx", line 260, in renpy.display.render.render
  File "renpy/text/text.py", line 2730, in render
    virtual_layout = Layout(self, width, height, renders, drawable_res=False, size_only=True)
                     ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/text/text.py", line 820, in __init__
    seg_glyphs, rtl = self.glyphs_paragraph(p, order)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "renpy/text/text.py", line 1673, in glyphs_paragraph
    rv.append((ts, ts.glyphs(s[offset:], self, l)))
                   ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^  
  File "renpy/text/text.py", line 372, in glyphs
    rv = fo.glyphs(s, level)
         ~~~~~~~~~^^^^^^^^^^
TypeError: ImageFont.glyphs() takes 2 positional arguments but 3 were given

Windows-11-10.0.26100-SP0 AMD64
Ren'Py 8.4.2.25090301+nightly
bitmap font demo 1.0
Wed Sep  3 19:29:49 2025
```
