### ISSUE TITLE
iOS 18 launch failures

### ISSUE THREAD

**Issue by blackcatstudiosdevelopment** [renpy/renpy#5852]
When building and testing for iOS 18 the app never launches. Below are the relevant traces but it appears as those something is either missing or the app container layout has changed in an unexpected way.

```
Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/[scrubbed]/Library/Developer/Xcode/DerivedData/SummonedByAccident-gsgdxirveoexaqbcubbrkwrhkzwg/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_22A3351/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file, no dyld cache), '/Library/Developer/CoreSimulator/Volumes/iOS_22A3351/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Users/[scrubbed]/Library/Developer/Xcode/DerivedData/SummonedByAccident-gsgdxirveoexaqbcubbrkwrhkzwg/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/C/Foundation' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_22A3351/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (no such file, no dyld cache), '/Library/Developer/CoreSimulator/Volumes/iOS_22A3351/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (no such file)
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/[scrubbed]/Library/Developer/Xcode/DerivedData/SummonedByAccident-gsgdxirveoexaqbcubbrkwrhkzwg/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_22A3351/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.0.simruntime/Contents/Resources/RuntimeRoot/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_22A3351/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file)
Type: stdio
```

```
Traceback (most recent call last):
  File "/Users/[scrubbed]/Library/Developer/CoreSimulator/Devices/B960CAD8-AC12-4B65-ABFE-E85BB3EE3AE5/data/Containers/Bundle/Application/A783F20B-7219-4FDA-A197-77269DF405D4/Summoned By Accident.app/base/main.py", line 303, in <module>
    main()
  File "/Users/[scrubbed]/Library/Developer/CoreSimulator/Devices/B960CAD8-AC12-4B65-ABFE-E85BB3EE3AE5/data/Containers/Bundle/Application/A783F20B-7219-4FDA-A197-77269DF405D4/Summoned By Accident.app/base/main.py", line 299, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "renpy/bootstrap.py", line 321, in bootstrap
  File "renpy/__init__.py", line 522, in import_all
ModuleNotFoundError: No module named 'renpy.audio.filter'
```

<img width="274" alt="Screenshot 2024-10-20 at 3 44 23 PM" src="https://github.com/user-attachments/assets/d32e95d1-c048-473e-9ea9-248116a53173">

Xcode 16.0 (16A242d)

Ren'Py 8.3.2.24090902

**Comment by renpytom** [comment]
Have you re-created your project under the new Ren'Py. Each time you update Ren'Py, you need to create a new iOS project.

**Comment by blackcatstudiosdevelopment** [comment]
I completely regenerated the Xcode project as you suggested and this now works.

I definitely didn't change Ren'Py versions so I'm not sure what conflicted but I'm set now. 🤷🏼‍♂️
