### ISSUE TITLE
renpy.load_surface() sometimes causes Exception in 8.3.3

### ISSUE THREAD

**Issue by point-dot** [renpy/renpy#5923]
Since 8.3.3 renpy.load_surface() sometimes causes a KeyError when I use it. After calling it at least twice it works as expected again.
(I use surface to calculate the bounding_rect so i can display an icon bove characters heads)

```
renpy.load_surface('images/npcs/belle/home/relaxing/0001.webp')
KeyError: <renpy.display.im.Image object ('images/npcs/belle/home/relaxing/0001.webp') at 0x0000000008005eb0>

Traceback (most recent call last):
  File "renpy/common/00console.rpy", line 719, in run
    result = renpy.python.py_eval(code)
  File "D:\Renpy\renpy-8.3.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Renpy\renpy-8.3.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
  File "D:\Renpy\renpy-8.3.3-sdk\renpy\display\im.py", line 2108, in load_surface
    return cache.get(image(im))
  File "D:\Renpy\renpy-8.3.3-sdk\renpy\display\im.py", line 384, in get
    self.kill(ce)
  File "D:\Renpy\renpy-8.3.3-sdk\renpy\display\im.py", line 397, in kill
    del self.cache[ce.what]
KeyError: <renpy.display.im.Image object ('images/npcs/belle/home/relaxing/0001.webp') at 0x0000000008005eb0>
```

**Comment by point-dot** [comment]
seems to work now 👍
