### ISSUE TITLE
the question takes minutes to load

### ISSUE THREAD

**Issue by dk** [renpy/renpy#5955]
Hello,

v8.3.3 takes several minutes to load on Windows-10-10.0.19045 / NVIDIA GeForce RTX 3070 driver version 32.0.15.6094. Antivirus disabled

here's the last lines of log.txt:

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.

and here's strace's last lines before it hangs:

--- Process 16264 loaded C:\Windows\System32\glu32.dll at 00007ffae4420000
--- Process 16264 loaded C:\Windows\System32\msctf.dll at 00007ffb3b0b0000
--- Process 16264 loaded C:\Windows\System32\AppXDeploymentClient.dll at 00007ffb312d0000

I tried to run it directly with python -m trace -t renpy.py the_question but my python-foo is not strong so I'm getting this error:

Traceback (most recent call last):                                                File "lib/python3.9/runpy.py", line 197, in _run_module_as_main                 File "lib/python3.9/runpy.py", line 87, in _run_code                            File "lib/python3.9/trace.py", line 740, in <module>                            File "lib/python3.9/trace.py", line 728, in main                                File "lib/python3.9/trace.py", line 450, in runctx                              File "renpy.py", line 304, in <module>                                            main()                                                                        File "renpy.py", line 300, in main                                                renpy.bootstrap.bootstrap(renpy_base)                                         File "D:\1\renpy-8.3.3-sdk\renpy\bootstrap.py", line 299, in bootstrap            gamedir = renpy.__main__.path_to_gamedir(basedir, name)                     AttributeError: module '__main__' has no attribute 'path_to_gamedir'

**Comment by renpytom** [comment]
That's not supported, as you're likely to be missing some libraries Ren'Py needs. (Perhaps even to properly handle errors.) 

You want to either run renpy.exe, or: 

lib\py3-windows-x86_64\python.exe renpy.py

**Comment by dk** [comment]
Yes what I meant is that I run your python, from lib, - of course.

**Comment by renpytom** [comment]
I don't think this is likely to be a problem with Ren'Py,. given that it starts fast for everyone else. You need to figure out what's wrong with your computer, assuming renpy.exe isn't working.

**Comment by dk** [comment]
I've seen the similar suggestion on the other tickets, trying to shift the onus to find whats wrong to the user. While in theory I dont mind recompiling the sdk and debugging it, because I have the capacity, I believe the whole angle of this is wrong. In ideal world, or at least as my experiece tells it, an application must adapt to variations in the setup, provide some debugging options, some ways to track errors etc etc and telling the user to figure out whats wrong with the computer is a bit amateurish. Esp that python v2-based sdk runs just fine, and renpy is a fairly simple application that doesn't use much of win32 graphics api, bot all standard stuff from gdi/gdi+/dwrite. I dont believe that there is anything wrong with my installation, and i dont agree that "other" have it ok because i've seen at least one other report where renpy takes minutes to load. However I"m still open for guidance with the recompiling and the debugging, if anything

**Comment by renpytom** [comment]
Thank you for your feedback.

**Comment by dk** [comment]
This is not resolved.
