### ISSUE TITLE
New archive.rpa fails to overwrite old after 6.18 Windows executable downloads 6.99-built update

### ISSUE THREAD

**Issue by weetabix-su** [renpy/renpy#653]
I updated our game's Ren'Py 6.18 build to it's most recent version built in Ren'Py 6.99. After the game restarts after update, the game's appearance didn't change as if the update didn't succeed. Checked updates again, and the screen says it's "up to date." Inspected the [game] folder and I found two RPA files: the old archive.rpa and an archive.rpa.new that's more than twice as big as the old one. 

![20150607](https://cloud.githubusercontent.com/assets/2226326/8020771/e4742cfc-0cb7-11e5-9db1-cccf4862994b.png)

Deleting the old archive.rpa and renaming the new one seems to do the trick, but I think the updater should do this by itself.

**Comment by weetabix-su** [comment]
UPDATE: Never mind. I think I found the culprit in update's log.txt
```
could not rename file C:\YHMVS-1.12a-developer\game/archive.rpa
could not rename file C:\YHMVS-1.12a-developer\renpy/common/DejaVuSans.ttf
R C:\YHMVS-1.12a-developer\renpy/common/DejaVuSans.ttf
Traceback (most recent call last):
  File "renpy/common/00updater.rpy", line 109, in process_deferred
    process_deferred_line(l)
  File "renpy/common/00updater.rpy", line 75, in process_deferred_line
    os.unlink(fn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\YHMVS-1.12a-developer\\renpy/common/DejaVuSans.ttf'
```
