### ISSUE TITLE
ui.interact doesn't work on some Android devices

### ISSUE THREAD

**Issue by Dreamtale** [renpy/renpy#696]
It happens in several cases, but the common thing is that it leads to ui.interact function. Traceback is pretty the same in every case:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00keymap.rpy", line 366, in <module>
error: Could not fetch native window

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-6.99.3\renpy\bootstrap.py", line 288, in bootstrap
  File "D:\renpy-6.99.3\renpy\main.py", line 434, in main
  File "D:\renpy-6.99.3\renpy\main.py", line 107, in run
  File "D:\renpy-6.99.3\renpy\execution.py", line 696, in run_context
  File "00start.rpyc", line 149, in script call
  File "00keymap.rpyc", line 358, in script
  File "D:\renpy-6.99.3\renpy\ast.py", line 785, in execute
  File "D:\renpy-6.99.3\renpy\python.py", line 1449, in py_exec_bytecode
  File "renpy/common/00keymap.rpy", line 366, in <module>
  File "D:\renpy-6.99.3\renpy\ui.py", line 277, in interact
  File "D:\renpy-6.99.3\renpy\display\core.py", line 2247, in interact
  File "D:\renpy-6.99.3\renpy\display\core.py", line 1464, in start
  File "D:\renpy-6.99.3\renpy\display\core.py", line 1677, in set_mode
  File "D:\renpy-6.99.3\renpy\display\swdraw.py", line 765, in set_mode
  File "pygame_sdl2/display.pyx", line 387, in pygame_sdl2.display.set_mode (gen/pygame_sdl2.display.c:5302)
  File "pygame_sdl2/display.pyx", line 108, in pygame_sdl2.display.Window.**init** (gen/pygame_sdl2.display.c:1967)
error: Could not fetch native window

Renpy 6.99.4 (disregard the name of the folder).

**Comment by renpytom** [comment]
Hm... The issue here seems to be that OpenGL is failing to initialize, and software rendering doesn't work.

Can you pull log.txt from one of the devices? That would help show what the device is, and why OpenGL ES is failing.

**Comment by Dreamtale** [comment]
Sun Jul 26 15:19:38 2015
Early init took 0.27s
Loader init took 0.11s
Loading error handling took 0.32s
Loading script took 50.16s
Loading persistent took 0.03s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 7.06s
Analyze and compile ATL took 2.34s
Index archives took 0.11s
Cleaning cache took 0.04s
Making clean stores took 0.00s
Creating interface object took 0.02s
Cleaning stores took 0.00s
Init translation took 0.17s
Build styles took 0.03s
Prepare screens took 2.94s
Running _start took 0.00s
Interface start took 0.30s

Windowed mode.
Could not get pygame screen: error('Could not fetch native window',)
Traceback (most recent call last):
  File "D:\renpy-6.99.3\renpy\error.py", line 208, in report_exception
  File "/home/tom/ab/android/python-for-android/build/python-install/lib/python2.7/platform.py", line 1575, in platform
  File "/home/tom/ab/android/python-for-android/build/python-install/lib/python2.7/platform.py", line 163, in libc_ver
IOError: [Errno 21] Is a directory: '/data/data/su.sovietgames.everlasting_summer/files'
Traceback (most recent call last):
  File "D:\renpy-6.99.3\renpy\error.py", line 208, in report_exception
  File "/home/tom/ab/android/python-for-android/build/python-install/lib/python2.7/platform.py", line 1575, in platform
  File "/home/tom/ab/android/python-for-android/build/python-install/lib/python2.7/platform.py", line 163, in libc_ver
IOError: [Errno 21] Is a directory: '/data/data/su.sovietgames.everlasting_summer/files'

**Comment by renpytom** [comment]
Unfortunately, I don't have a good answer to this. SDL2, a library Ren'Py uses, is unable to open the screen up. What kind of device is it, and what version of Android does it use?

**Comment by Dreamtale** [comment]
Some examples:
HTC Desire 310, 4.2.2
Asus Nexus 7 2013 android 5.1.1
But really there are a lot more - I can't find any regularity with the exact device or Android version myself...

**Comment by renpytom** [comment]
I'm assuming this has been fixed by now, so closing it.
