### ISSUE TITLE
Newer versions of cython can generate Python longs.

### ISSUE THREAD

**Issue by jbeich** [renpy/renpy#778]
I get the following error when trying to run 32bit renpy >= 6.99.6 within chroot under amd64 on FreeBSD 11. Bisecting leads to 22a1bc6.

```shell
$ pkg info -x cython sdl
cython-0.23.4
py27-game_sdl2-6.99.7
sdl2-2.0.3_6
sdl2_image-2.0.0_7
sdl2_mixer-2.0.0_9
sdl2_ttf-2.0.12_5
```
```shell
$ (cd module; RENPY_DEPS_INSTALL="/usr/local" python2.7 setup.py install)
[...]
$ python2.7 renpy.py
TypeError("'long' object is not iterable",)

Full traceback:
  File "renpy/common/00start.rpy", line 150, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 378, in script
    $ __gl_test()
  File "/home/foo/renpy/renpy/ast.py", line 805, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/foo/renpy/renpy/python.py", line 1460, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00gltest.rpy", line 378, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 304, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 321, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
  File "/home/foo/renpy/renpy/ui.py", line 277, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/foo/renpy/renpy/display/core.py", line 2325, in interact
    self.start()
  File "/home/foo/renpy/renpy/display/core.py", line 1513, in start
    self.set_mode()
  File "/home/foo/renpy/renpy/display/core.py", line 1748, in set_mode
    if draw.set_mode(virtual_size, physical_size, fullscreen):
  File "renpy/gl/gldraw.pyx", line 191, in renpy.gl.gldraw.GLDraw.set_mode (gen/renpy.gl.gldraw.c:2766)
    renpy.display.interface.post_init()
  File "/home/foo/renpy/renpy/display/core.py", line 1562, in post_init
    pygame.event.set_blocked(i)
  File "src/pygame_sdl2/event.pyx", line 422, in pygame_sdl2.event.set_blocked (gen/pygame_sdl2.event.c:8126)
TypeError: 'long' object is not iterable

While running game code:
  File "renpy/common/00start.rpy", line 150, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 378, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 378, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 304, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 321, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
TypeError: 'long' object is not iterable
TypeError("'long' object is not iterable",)

Full traceback:
  File "/home/foo/renpy/renpy/bootstrap.py", line 281, in bootstrap
    renpy.main.main()
  File "/home/foo/renpy/renpy/main.py", line 463, in main
    run(restart)
  File "/home/foo/renpy/renpy/main.py", line 139, in run
    renpy.execution.run_context(True)
  File "/home/foo/renpy/renpy/execution.py", line 714, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 150, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 378, in script
    $ __gl_test()
  File "/home/foo/renpy/renpy/ast.py", line 805, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/foo/renpy/renpy/python.py", line 1460, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00gltest.rpy", line 378, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 304, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 321, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
  File "/home/foo/renpy/renpy/ui.py", line 277, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/foo/renpy/renpy/display/core.py", line 2325, in interact
    self.start()
  File "/home/foo/renpy/renpy/display/core.py", line 1513, in start
    self.set_mode()
  File "/home/foo/renpy/renpy/display/core.py", line 1748, in set_mode
    if draw.set_mode(virtual_size, physical_size, fullscreen):
  File "renpy/gl/gldraw.pyx", line 191, in renpy.gl.gldraw.GLDraw.set_mode (gen/renpy.gl.gldraw.c:2766)
    renpy.display.interface.post_init()
  File "/home/foo/renpy/renpy/display/core.py", line 1562, in post_init
    pygame.event.set_blocked(i)
  File "src/pygame_sdl2/event.pyx", line 422, in pygame_sdl2.event.set_blocked (gen/pygame_sdl2.event.c:8126)
TypeError: 'long' object is not iterable

While running game code:
  File "renpy/common/00start.rpy", line 150, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 378, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 378, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 304, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 321, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
TypeError: 'long' object is not iterable
Traceback (most recent call last):
  File "/home/foo/renpy/renpy/editor.py", line 92, in open
    subprocess.call([ "xdg-open", filename ]) #@UndefinedVariable
  File "/usr/local/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
32bit
```python
>>> import pygame_sdl2.event
>>> pygame_sdl2.event.get_standard_events()
[0L, 256L, 258L, 259L, 260L, 261L, 262L, 257L, 1026L, 1539L, 1027L, 512L, 1540L, 768L, 1541L, 4096L, 1542L, 1024L, 8192L, 513L, 1536L, 769L, 1792L, 2050L, 1025L, 2048L, 2304L, 1616L, 1617L, 1618L, 1619L, 1537L, 1621L, 770L, 1793L, 2049L, 1538L, 771L, 1620L, 1794L, 65532, 65533, 65534, 65535L]
>>> for i in pygame_sdl2.event.get_standard_events():
...	pygame_sdl2.event.set_blocked(i)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pygame_sdl2/event.pyx", line 422, in pygame_sdl2.event.set_blocked (gen/pygame_sdl2.event.c:8126)
TypeError: 'long' object is not iterable
```
64bit
```python
>>> import pygame_sdl2.event
>>> pygame_sdl2.event.get_standard_events()
[0, 256, 258, 259, 260, 261, 262, 257, 1026, 1539, 1027, 512, 1540, 768, 1541, 4096, 1542, 1024, 8192, 513, 1536, 769, 1792, 2050, 1025, 2048, 2304, 1616, 1617, 1618, 1619, 1537, 1621, 770, 1793, 2049, 1538, 771, 1620, 1794, 65532, 65533, 65534, 65535]
>>> for i in pygame_sdl2.event.get_standard_events():
...	pygame_sdl2.event.set_blocked(i)
...
```

**Comment by renpytom** [comment]
This looks like a freebsd-only thing, as I was able to run the code under 32 bit Linux and had no problems. It's weird that 32-bit numbers are becoming longs for some reason - I don't think that's right, and it might point a problem in cython or python.

Can you tell me what sys.maxint is?

Still, it's easy enough to allow longs to be used as event types. The change was made to pygame_sdl2, so you'll want to grab the commit linked above and compile against that.

**Comment by jbeich** [comment]
Let's downgrade Cython:
- 0.23.4 -> 0.23.0 didn't help
- 0.23.4 -> 0.22.1 fixed the issue

Notice, some values from `.even_names` suspiciously lack **L** suffix.
```python
>>> for i in pygame_sdl2.event.get_standard_events():
...     if type(i) == int:
...             { i: pygame_sdl2.event.event_name(i) }
...
{65532: 'VIDEOEXPOSE'}
{65533: 'VIDEORESIZE'}
{65534: 'ACTIVEEVENT'}
```

It's probably related to the following generated code where i386 has `sizeof(SDL_EventType) == sizeof(long)`, so promoted to `PyLong`. However, anonymous `enum` in .pxd becomes literal `int` which is signed thus `PyInt`.
```c
// Before 0.23
__pyx_t_2 = PyInt_FromLong(SDL_QUIT);

// After 0.23
__pyx_t_2 = __Pyx_PyInt_From_SDL_EventType(SDL_QUIT);
...
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_SDL_EventType(SDL_EventType value) {
    const SDL_EventType neg_one = (SDL_EventType) -1, const_zero = (SDL_EventType) 0;
    const int is_unsigned = neg_one > const_zero;
    if (is_unsigned) {
        if (sizeof(SDL_EventType) < sizeof(long)) {
            return PyInt_FromLong((long) value);
        } else if (sizeof(SDL_EventType) <= sizeof(unsigned long)) {
            return PyLong_FromUnsignedLong((unsigned long) value);
        } else if (sizeof(SDL_EventType) <= sizeof(unsigned PY_LONG_LONG)) {
            return PyLong_FromUnsignedLongLong((unsigned PY_LONG_LONG) value);
        }
    } else {
        if (sizeof(SDL_EventType) <= sizeof(long)) {
            return PyInt_FromLong((long) value);
        } else if (sizeof(SDL_EventType) <= sizeof(PY_LONG_LONG)) {
            return PyLong_FromLongLong((PY_LONG_LONG) value);
        }
    }
...
```

> Can you tell me what sys.maxint is?

```python
>>> sys.maxint
2147483647
```

**Comment by renpytom** [comment]
I'm reopening this, since I think it's something I'll need to audit the Ren'Py and Pygame_SDL2 code for.

**Comment by jbeich** [comment]
Bisecting leads to cython/cython@4277712 and probably reflected in CHANGES.rst:
```ReST
0.23 (2015-08-08)
=================
Bugs fixed
----------
* Fixed type errors in conversion enum types to/from Python.  Note that
  this imposes stricter correctness requirements on enum declarations.
```
