### ISSUE TITLE
Can't build at all

### ISSUE THREAD

**Issue by adnathanail** [renpy/renpy#804]
I have downloaded ANT and the APK however when trying to build the example project it fails, I have gone to all the locations it mentions and they all exist despite the fact that it's error message appears to be "No such file or directory" however I don't claim to know anything about Java, hence why I am using this!
The contents of android.txt is below.

Updating source code.

Updating build files.
Resolved location of library project to: /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/extras/google/play_apk_expansion/downloader_library
Updated and renamed default.properties to project.properties
Updated local.properties
Added file ./build.xml
Updated file ./proguard-project.txt

Creating assets directory.

Packaging internal data.

I'm using Ant to build the package.
Buildfile: /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/build.xml
  [taskdef] Could not load definitions from resource emma_ant.properties. It could not be found.

-set-mode-check:

-set-release-mode:

-release-obfuscation-check:
     [echo] proguard.config is ${proguard.config}

-pre-build:

-check-env:
 [checkenv] Android SDK Tools Revision 23.0.0
 [checkenv] Installed at /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23

-setup:
     [echo] Project Name: Testing-1.0
  [gettype] Project Type: Application

-build-setup:
[getbuildtools] Using latest Build Tools: 20.0.0
     [echo] Resolving Build Target for Testing-1.0...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
     [echo] ----------
     [echo] Resolving Dependencies for Testing-1.0...
[dependency] Library dependencies:
[dependency] 
[dependency] ------------------
[dependency] Ordered libraries:
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'release'...
  [taskdef] Could not load definitions from resource emma_ant.properties. It could not be found.

nodeps:

-set-mode-check:

-set-release-mode:

-release-obfuscation-check:
     [echo] proguard.config is ${proguard.config}

-pre-build:

-check-env:
 [checkenv] Android SDK Tools Revision 23.0.0
 [checkenv] Installed at /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23

-setup:
     [echo] Project Name: library
  [gettype] Project Type: Android Library

-build-setup:
[getbuildtools] Using latest Build Tools: 20.0.0
     [echo] Resolving Build Target for library...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/extras/google/play_licensing/library/bin/rsObj
    [mkdir] Created dir: /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/extras/google/play_licensing/library/bin/rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for library...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------

-code-gen:
[mergemanifest] No changes in the AndroidManifest files.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...

BUILD FAILED
/home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/tools/ant/build.xml:601: The following error occurred while executing this line:
/home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/tools/ant/build.xml:653: The following error occurred while executing this line:
/home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/tools/ant/build.xml:698: Execute failed: java.io.IOException: Cannot run program "/home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/build-tools/20.0.0/aapt" (in directory "/home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/extras/google/play_licensing/library"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:41)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at com.android.ant.AaptExecTask.execute(AaptExecTask.java:699)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:306)
	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:221)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 68 more

Total time: 4 seconds

The build seems to have failed.

**Comment by renpytom** [comment]
Please ensure your system is capable of running 32 bit linux binaries, especially 
/home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/build-tools/20.0.0/aapt

(This isn't a bug in Ren'Py, so I'm closing this, but feel free to reply.)

**Comment by adnathanail** [comment]
Hi,
I made my system able to run 32-bit binaries, I think, however now I have a different error message:


Updating source code.

Updating build files.
Resolved location of library project to: /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/extras/google/play_apk_expansion/downloader_library
Updated and renamed default.properties to project.properties
Updated local.properties
Added file ./build.xml
Updated file ./proguard-project.txt




Creating assets directory.

Packaging internal data.

I'm using Ant to build the package.
Buildfile: /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/build.xml
  [taskdef] Could not load definitions from resource emma_ant.properties. It could not be found.

-set-mode-check:

-set-release-mode:

-release-obfuscation-check:
     [echo] proguard.config is ${proguard.config}

-pre-build:

-check-env:
 [checkenv] Android SDK Tools Revision 23.0.0
 [checkenv] Installed at /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23

-setup:
     [echo] Project Name: Testing-1.0
  [gettype] Project Type: Application

-build-setup:
[getbuildtools] Using latest Build Tools: 20.0.0
     [echo] Resolving Build Target for Testing-1.0...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
     [echo] ----------
     [echo] Resolving Dependencies for Testing-1.0...
[dependency] Library dependencies:
[dependency] 
[dependency] ------------------
[dependency] Ordered libraries:
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'release'...
  [taskdef] Could not load definitions from resource emma_ant.properties. It could not be found.

nodeps:

-set-mode-check:

-set-release-mode:

-release-obfuscation-check:
     [echo] proguard.config is ${proguard.config}

-pre-build:

-check-env:
 [checkenv] Android SDK Tools Revision 23.0.0
 [checkenv] Installed at /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23

-setup:
     [echo] Project Name: library
  [gettype] Project Type: Android Library

-build-setup:
[getbuildtools] Using latest Build Tools: 20.0.0
     [echo] Resolving Build Target for library...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/extras/google/play_licensing/library/bin/rsObj
    [mkdir] Created dir: /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/extras/google/play_licensing/library/bin/rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for library...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------

-code-gen:
[mergemanifest] No changes in the AndroidManifest files.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [aapt] /home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/build-tools/20.0.0/aapt: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

BUILD FAILED
/home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/tools/ant/build.xml:601: The following error occurred while executing this line:
/home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/tools/ant/build.xml:653: The following error occurred while executing this line:
/home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/tools/ant/build.xml:698: null returned: 127

Total time: 7 seconds




The build seems to have failed.

**Comment by renpytom** [comment]
So, the problem line is:

/home/alexander/Downloads/renpy-6.99.7-sdk/rapt/android-sdk-r23/build-tools/20.0.0/aapt: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

It says that the 32-bit version of libz.so.1 is missing. So you'd have to install that.

According to  http://developer.android.com/sdk/installing/index.html?pkg=tools the commands

sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libncurses5:i386 libstdc++6:i386 zlib1g:i386

might do the job.

**Comment by adnathanail** [comment]
Hi,

I had already installed those but I went to the page you linked and attempted to install ia32-libs which said it was deprecated and from there I installed lib32z1 lib32ncurses5 amd lib32bz2-1.0 as well as sun-java6-jdk as recommended by that page and something worked as I can now compile my programme into and apk!

Thanks for your help. :+1:
